### ISSUE TITLE
Any example on dynamic chunks will be very helpful

### ISSUE THREAD

**Issue by abhinavsingi** [faceyspacey/extract-css-chunks-webpack-plugin#10]
This is for understanding this particular plugin.

In our app we have server side rendering + dynamic routing.
We use React, Redux, Webpack.

What I'm trying to understand or maybe if an example can be provided which would help in making us understand how to use this plugin for our use case. I have been able to successfully create chunks and css files based on the README examples. What I'm struggling with is how to apply them in our app.

Top queries:

1. Where will be `.css` loaded in server side?
2. For dynamic routing - how will we ensure that `.no_css.js` is loaded on server side and `.js` is loaded on client side? (Is this even a valid query?)
3. For server side rendering and client side rendering - will we have to do anything different wrt this plugin?
4. If an example can be provided on how to use this plugin for multiple dynamic routing and above, it'll be of great help.

Thanks in advance and thank you for making this plugin.
I found this plugin in https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/106 and https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/120.
Please let me know in case my queries are not clear.

**Comment by faceyspacey** [comment]
@abhinavsingi 

Check this article out and let me know if u still need help:

https://medium.com/@faceyspacey/code-cracked-for-code-splitting-ssr-in-reactlandia-react-loadable-webpack-flush-chunks-and-1a6b0112a8b8

...basically u gotta use the package described in the article, `webpack-flush-chunks`, which automates this for you. it automatically sends `.no_css.js` in initial renders and automatically sends `.js` files that contain css in async imports. 

it's all designed to make this as simple as possible for you. use one of the "universal webpack" boilerplates and it should all make sense.
