### ISSUE TITLE
HMR not working

### ISSUE THREAD

**Issue by MartinCerny-awin** [faceyspacey/extract-css-chunks-webpack-plugin#105]
I am using 3.1.1. version and I have hot enabled, but the HMR is not working. I can see correct output in browser console:
```
[HMR] Checking for updates on the server...
console.js:35 [HMR] Updated modules:
console.js:35 [HMR]  - ./src/modules/visitor/practice/joinUsView/JoinUsView.css
console.js:35 [HMR] App is up to date.
console.js:35 [HMR] Reload all css
```
but the file is empty and the page is not reloaded.

**Comment by ScriptedAlchemy** [comment]
Found the issue, it was in-part your project build and my plugin. Will pr
