### ISSUE TITLE
[Question/request] A way to remove shared css from the chunks and into their own chunk.

### ISSUE THREAD

**Issue by Pixelatex** [faceyspacey/extract-css-chunks-webpack-plugin#109]
So the situation is like this, it's kinda of a component library and every component has an entry point.

```
-- Component.js
    --> imports Component.sass
        --> imports Global.sass
```
_Global.sass_ contains shared variables like fonts, colors, etc...

This results in the following output:
```
Component.js
/css
- Component.css (contains the Global.sass inline)
```

What I want to achieve is the following:
```
Component.js
/css
- Component.css (only contains global.sass and an import for ./Global.css)
- Global.css (shared chunk)
```
Is this possible with extractcsschunks somehow?

**Comment by ScriptedAlchemy** [comment]
Yep. Use sass resources loader. 

It’s simple, but just  injects the contents of whatever files you want  ahead of the file about to compile 


I use it for mixins, variables, functions.
