### ISSUE TITLE
Question: webpack 1 version?

### ISSUE THREAD

**Issue by cvbuelow** [faceyspacey/extract-css-chunks-webpack-plugin#11]
What would it take to make a webpack 1 version of this plugin?

**Comment by faceyspacey** [comment]
I likely won't get to this, but I'd compare the initial commits here and remake it. I tried to make it so most the work got done in one condensed initial commit so anyone could easily view the changes:

https://github.com/faceyspacey/extract-css-chunks-webpack-plugin/commit/849ad54dc555a31dbb793177a83e1c0b053426ee

**Comment by cvbuelow** [comment]
Ok thanks 👍
