### ISSUE TITLE
HMR does not work in react-static

### ISSUE THREAD

**Issue by KidkArolis** [faceyspacey/extract-css-chunks-webpack-plugin#110]
To reproduce:

1. git clone git@github.com:nozzle/react-static.git
2. cd react-static
3. git checkout v6
4. yarn
5. yarn add extract-css-chunks-webpack-plugin
6. yarn build
7. yarn link
8. cd ~/Desktop
9. react-static create
10. cd my-static-site
11. yarn link react-static
12. react-static start
13. make a change to app.css – it's not hot reloading

**Comment by ScriptedAlchemy** [comment]
Likely just needs to be updated again

Thanks, I’ll handle it in a couple

**Comment by ScriptedAlchemy** [comment]
Finally found it!
