### ISSUE TITLE
HMR wont work with chunked scss

### ISSUE THREAD

**Issue by oskarleonard** [faceyspacey/extract-css-chunks-webpack-plugin#111]
1. Check the version of package you are using. If it's not the newest version, update and try again (see changelog while updating!).
Latest

2. If the issue is still there, write a minimal project showing the problem and expected output.
https://github.com/madeagency/reactivity

3. Link to the project and mention Node version and OS in your report.
https://github.com/madeagency/reactivity

I cannot get hmr to work with scss, only non chuncked scss (main.scss) gets hmr. My "solution" so far is to use style-loader instead of ExtractCssChunks.loader in dev but that kind of bread server styles (not looking as nice as in the universal demo)

**Comment by oskarleonard** [comment]
Super!  :D.  Had just tried `hot: true`, didnt know about the other options, only using `reloadAll: true` solved everything, works so much faster then style loader.

**Comment by ScriptedAlchemy** [comment]
yeah i realized today theres no documentation, writing it as we speak

**Comment by oskarleonard** [comment]
That would be great especially documenting the API :). Maybe while you are in the process you could modify this line:
`    new ExtractCssChunks({hot:true}), //if you want HMR - we try to automatically inject hot reloading but if it's not working, add it to the config
`
to
`    new ExtractCssChunks({hot: true, reloadAll: true, cssModules: true}), //if you want HMR - we try to automatically inject hot reloading but if it's not working, add it to the config
`

**Comment by ScriptedAlchemy** [comment]
Added some docs!
