### ISSUE TITLE
HotModuleReplacement. Js cannot run on IE11

### ISSUE THREAD

**Issue by heruiwoniou** [faceyspacey/extract-css-chunks-webpack-plugin#118]
Version: 3.2.1-alpha.1

Reason: IE11 cannot resolve the features of ES6 such as const. 

Can it fix the problem?

Thanks.

**Comment by ScriptedAlchemy** [comment]
Open a pull request and re-configure my babel or eslint builds to stop it from breaking :)

**Comment by heruiwoniou** [comment]
I have already submitted PR, I don't know if there is any irregularity, this is my first time to submit PR on Github.
