### ISSUE TITLE
Crashed on low version devices

### ISSUE THREAD

**Issue by Jemair** [faceyspacey/extract-css-chunks-webpack-plugin#121]
**What happend**
I found my web app crashed when developing on ios 9, seems like this plugin caused

**reason**
You didn't compile `const` and `let` in your build version. And upon strict mode, they will not be recognized on iOS < 9 & android < 4.4.4. Besides, it is likely be unsupported on IE9
![image](https://user-images.githubusercontent.com/20502467/47543143-652f3a00-d913-11e8-90fc-029beec51869.png)

I'm working on a pr to fix this problem. Or you may have some other thought, let me know please.
Thanks

**Comment by ScriptedAlchemy** [comment]
I’ll defiantly merge it! If you can fix our Babel config or PR us. I’ll be most appreciative

**Comment by Jemair** [comment]
> I’ll defiantly merge it! If you can fix our Babel config or PR us. I’ll be most appreciative

I remembered you have merged it month ago. I forgot closing the issue
https://github.com/faceyspacey/extract-css-chunks-webpack-plugin/pull/122
Thanks
