### ISSUE TITLE
README > webpack.config.js > optimization

### ISSUE THREAD

**Issue by oskarleonard** [faceyspacey/extract-css-chunks-webpack-plugin#126]
Would be great to explain why those optimization settings are needed, i thought that the default optimization in webpack 4 are the recommended, so i never added the optimization settings in this readme to my webpack. 

If one want to use `UglifyJSPlugin` shouldnt `npm install uglifyjs-webpack-plugin --save-dev` `const UglifyJsPlugin = require('uglifyjs-webpack-plugin');` be added to the top part of that code snippet? https://webpack.js.org/plugins/uglifyjs-webpack-plugin/

As for the `// NEEDED BOTH IN PROD AND DEV BUILDS`  (which i also didnt include)  is `name: 'bootstrap'` some internal HMR thing? Would be great to add that HMR wont work 100% without that part (but everything else seemed to work), or more specifically, changing names of files which where dynamically imported, crashed the app and gave this error `utils.js:58 chunk not available for synchronous require yet: ...` . But this was solved by adding the optimisation config below "// NEEDED BOTH IN PROD AND DEV BUILDS" :) .

**Comment by ScriptedAlchemy** [comment]
Heya I’m mega swamped with an ungodly backlog. Would you be willing to PR me?
