### ISSUE TITLE
Load all css files of page on production with ssr based on express.js

### ISSUE THREAD

**Issue by believer-ufa** [faceyspacey/extract-css-chunks-webpack-plugin#129]
Hello! Many thanks for that plugin. Please can you explain: it is possible to use it with react-router v3 + ssr and get links to all css chunks in responsed HTML from server? Now i trying do it, but finally i see only one link to main CSS chunk on production mode. After building production files, i have next html template in `build` folder:

```
<!DOCTYPE html>
<html {{ HTML_ATTRIBUTES }}>
<head>
  {{ HEAD }}
<link href="/assets/frontend.main.build.f7a7ca3edaf9fda4be42.css" rel="stylesheet"><link rel="preload" href="/assets/frontend.main.build.658ff508bca3f57f2bb5.js" as="script"><link rel="prefetch" href="/assets/frontend.main.build.658ff508bca3f57f2bb5.js"></head>
<body>
  <div id="portals"></div>
  <div id="root">{{ APP_CONTENT }}</div>
  <script src="https://cdn.polyfill.io/v2/polyfill.min.js"></script>
  <script>window.CLIENT_PARAMS = {{ CLIENT_PARAMS }}</script>
<script type="text/javascript" src="/assets/frontend.main.build.658ff508bca3f57f2bb5.js"></script></body>
</html>
```

And that file loads by our SSR code based on express.js.

Please can you explain: we can get information about used CSS chunks on requested page inside our express.js serverside code?

**Comment by ScriptedAlchemy** [comment]
Are you webpack 3? Or 4? 

You can still output them form flush chunks with 
"cssHash"

https://github.com/faceyspacey/redux-first-router-demo/blob/5214c1983e6b68022bc9d127eb26403ac6b3e4b1/server/render.js#L34


And 
https://github.com/faceyspacey/redux-first-router-demo/blob/5214c1983e6b68022bc9d127eb26403ac6b3e4b1/server/render.js#L1


Hope this helps
