### ISSUE TITLE
Make release

### ISSUE THREAD

**Issue by SvyatoslavPozhydaev** [faceyspacey/extract-css-chunks-webpack-plugin#134]
1. i use last version `"extract-css-chunks-webpack-plugin": "^3.2.1",`
2. last version not include commit https://github.com/faceyspacey/extract-css-chunks-webpack-plugin/commit/bc017ee5c767cb20c0aa140a545addcf60dc2855
this commit contain change for use in old browser

**Comment by ScriptedAlchemy** [comment]
Releases should he automated, ill do a version bump to make sure. Someone didn’t follow the semantic release commit messages and probbably failed the release system. No problem. Give me few hours

**Comment by ScriptedAlchemy** [comment]
Done
