### ISSUE TITLE
HMR not working on IE11 with v3.3.0

### ISSUE THREAD

**Issue by borisding** [faceyspacey/extract-css-chunks-webpack-plugin#138]
Hi!

Just tried with the newest version and things broken on IE11 due to ES6 syntax in `hotModuleReplacement.js`.

Not sure if IE11 is still supported?

Thanks!

**Comment by ScriptedAlchemy** [comment]
PR me a fix and we will support it. This has happened before.

**Comment by iiroj** [comment]
I guess this issue has resurfaced in `v3.3.2`, with commit [43e1672](https://github.com/faceyspacey/extract-css-chunks-webpack-plugin/commit/43e1672#diff-e56633f72ecc521128b3db6586074d2cL9)

**Comment by ScriptedAlchemy** [comment]
Semantic releases was broken for a long time, I’d been manually doing it. It’s playing catch-up now that i fixed it. Lol
