### ISSUE TITLE
Option "orderWarning" is ineffective

### ISSUE THREAD

**Issue by eliseumds** [faceyspacey/extract-css-chunks-webpack-plugin#142]
Commit https://github.com/faceyspacey/extract-css-chunks-webpack-plugin/commit/49933629aa9ab0bc6376c961385c4c920496c89c#diff-1fdf421c05c1140f6d71444ea2b27638L542 removed the logic that addresses the option *orderWarning*. It's still documented. Latest working commit: https://github.com/faceyspacey/extract-css-chunks-webpack-plugin/commit/acbe5b08934d39d6ab1bfbf3a4f16c654c7327f1#diff-1fdf421c05c1140f6d71444ea2b27638. Was it on purpose?

**Comment by ScriptedAlchemy** [comment]
Following the webpack conventions as we are planning to merge the two projects. 

I can update the docs or bring it back for the time being

**Comment by eliseumds** [comment]
Oh, I see. That's good news then. I was just wondering if the way the plugin works has changed considerably but it looks like it's all good after upgrading.

**Comment by davidcostadev** [comment]
I`m need of this option too :-)

**Comment by ScriptedAlchemy** [comment]
Open a pr and I’ll bring it back. Just copy paste whatever change and there you have it. My pull request if open to mini css so PR as you wish. I’ll maintain both, but it’s in the community’s hands :) 

@davidcostadev

**Comment by ScriptedAlchemy** [comment]
Ill have to re-check this. I'm not 100% sure we had tests till i started working on mini-css (btw I'm merging this plugin into mini-css)

Ive got a working copy that ill look at releasing as a breaking change, it should provide more stability and also resolve multiple issues

**Comment by ScriptedAlchemy** [comment]
Ill push out a beta tonight

**Comment by ScriptedAlchemy** [comment]
okay, theres a new 'next' version on npm, its a major rewrite. Working on docs now
