### ISSUE TITLE
normalize-url dependency causing error

### ISSUE THREAD

**Issue by rajatbarman** [faceyspacey/extract-css-chunks-webpack-plugin#145]
extract-css-chunks-webpack-plugin 3.3.2
node -v 8.11.1
npm -v 5.6.0
webpack 4.8.3

Module parse failed: Unexpected token (22:4)
You may need an appropriate loader to handle this file type.
| 		removeDirectoryIndex: false,
|     sortQueryParameters: true,
|     ...options
| 	};
|

This comes from normalize-url/index.js which is using the object spread operator. Converting to Object.assign works.

**Comment by manniL** [comment]
related: https://github.com/nuxt/nuxt.js/issues/5065

**Comment by ScriptedAlchemy** [comment]
Mind opening a pull request? I'm merging this project with mini-css-extract so it'll be of great help

**Comment by ScriptedAlchemy** [comment]
@manniL what fix can i implement for you?
Does downgrading normalize back to a previous major version help?

**Comment by manniL** [comment]
@ScriptedAlchemy I'm not sure actually :see_no_evil: cc @clarkdo / @pi0

**Comment by clarkdo** [comment]
@ScriptedAlchemy Since normalize-ur is for nodejs, so could we use other alternative lib for hot-loader in browser?

**Comment by ScriptedAlchemy** [comment]
Anyone know of an alternative, otherwise I’ll downgrade the version used and push a beta for someone to test

**Comment by rajatbarman** [comment]
This commit broke things
https://github.com/sindresorhus/normalize-url/commit/ee7e2c5efc59c31e5831ef8d4c1a1ec0694cfaac

I guess downgrading to v3.3.0 should work.

**Comment by clarkdo** [comment]
Downgrading can be a quick fix for now.

**Comment by rajatbarman** [comment]
https://github.com/faceyspacey/extract-css-chunks-webpack-plugin/pull/148

**Comment by rajatbarman** [comment]
@ScriptedAlchemy would really help if this could be resolved fast :)

**Comment by ScriptedAlchemy** [comment]
Awesome, this ought to fix so failing tests over at webpack too. 

Thanks 🙏

**Comment by rajatbarman** [comment]
Thank you.
