### ISSUE TITLE
Doesn't play nicely with hard-source-webpack-plugin.

### ISSUE THREAD

**Issue by phyllisstein** [faceyspacey/extract-css-chunks-webpack-plugin#15]
Hey there! First of all, thank you for your incredible work on this plugin---you've single-handedly rescued me from using CSS in JS, and I couldn't be more grateful.

That said, I've noticed that it doesn't play nicely with [`hard-source-webpack-plugin`](https://github.com/mzgoddard/hard-source-webpack-plugin)'s caching features. When built with a `hard-source` cache present, no CSS is emitted at all; when built for the first time, or when `hard-source` is generating a new cache, the CSS is emitted as expected.

I've dropped a quick-'n'-dirty repro repo at <https://github.com/phyllisstein/css-chunks-hard-source>; it's not much, but it does the trick. I'm happy to furnish any color I can if it's useful for troubleshooting! For the time being I've just nixed the `hard-source` plugin, but it'd be great to reconcile the issues between these two.

**Comment by faceyspacey** [comment]
Thanks for reporting this brother. I'll look into it. Getting this to play nicely with as many plugins as possible is important. Hopefully we find no more than core set of issues that applies to 80% of plugins.

**Comment by faceyspacey** [comment]
Hard source is now working with the latest stuff:

https://medium.com/faceyspacey/webpacks-import-will-soon-fetch-js-css-here-s-how-you-do-it-today-4eb5b4929852

Though it's slower than if you didn't use it and may not be worth it. The Autodll Webpack Plugin package works nicely though.

**Comment by Crazymax11** [comment]
Reproduced with 
"extract-css-chunks-webpack-plugin": "^2.0.8"
"hard-source-webpack-plugin": "^0.4.9"
 "webpack": "^3.3.0"

**Comment by faceyspacey** [comment]
...that's unfortunate. Unfortunately i think it's just gonna be too slow to work with hard-source anyway. It's supposed to get faster, not slower. I'm not exactly sure what that's about.

It's good you posted in the hard-source repo. Those guys may have a better idea. I'll chime in there.
