### ISSUE TITLE
Do you support nuxt. js? How do I configure it?

### ISSUE THREAD

**Issue by bigHead-zhu** [faceyspacey/extract-css-chunks-webpack-plugin#152]
Sass was used in my project and configuration error was reported.
![image](https://user-images.githubusercontent.com/30432817/54576865-afd16000-4a34-11e9-9810-60f3e77ffbee.png)
and My configuration is as follows
![image](https://user-images.githubusercontent.com/30432817/54577023-22424000-4a35-11e9-9700-6e1c53baea4b.png)

**Comment by ScriptedAlchemy** [comment]
Those look like js comments. Maybe try updating? I know nuxt works with this plugin

**Comment by manniL** [comment]
@bigHead-zhu Nuxt already uses it under the hood :D

See https://nuxtjs.org/api/configuration-build/#extractcss

**Comment by ScriptedAlchemy** [comment]
Looks like @manniL moved over to mini-CSS, i merged this project with that one. Hence how it has HMR. 

Wouldnt mind a plug/shoutout if you're into that kinda thing ;)
