### ISSUE TITLE
Prevent emit js chunk when css chunk, imported in js is emited (css file changed)

### ISSUE THREAD

**Issue by 7iomka** [faceyspacey/extract-css-chunks-webpack-plugin#154]
Hello my dear friend.
I switched from 3 to 4 versions of the webpack, and have problems reloading the page using the browsersync (as standalone package, not webpack plugin) after I make changes to the style file. I found out about this plugin here. I shot a separate video with a demonstration of my software environment.
extract-text-webpack-plugin on webpack 4 while it still works, and everything works as it should (except for the fact that all chunks are always generated), browsersync see like only css-chunk was emitted (file-changed), but no js, like in css-mini-extract-plugin.
In my env. I do not have access to html via webpack.
I use the pug as template engine separately and in development mode, the server is launched on Express which does not physically compile the files, but holds and sends the contents from the memory. therefore, templates must have static names on the connected resources.
In my case, each page (for example, index) includes common.js, index.js scripts and style files of the same name.
 as an entry, an array of these js files is given to the webpack; within these js files, first of all, there is an import of the same-name style file, which the extract-plugin exports to the build folder to which the express server is configured and everything works.
But even on the 3rd webpack, I was embarrassed by the fact that, while saving any css file, the changes of all entrises triggered. That is, the last modified date of those in the build folder was always updated, but somehow the extract-text-webpack-plugin functioned differently than the mini-css-extract plugin, because browsersync configured to watch the build of the folder in the first case noticed changes only in styles , and now notices that js has changed .. 
___
**Demo**: https://cl.ly/37b5d3cfc2b0
Short screenshot (after dev style file changed): ![image](https://user-images.githubusercontent.com/18473137/54779354-018e0c00-4c28-11e9-8e42-29e3b6ed9992.png)

**Comment by ScriptedAlchemy** [comment]
if you are running in dev, then its likely the HMR part. Doesn't do this in prodcution

**Comment by 7iomka** [comment]
> if you are running in dev, then its likely the HMR part. Doesn't do this in prodcution

I have to do it in dev mode because I have no ready working solution in setup express + pug and hmr + webpack. That is why I used not always the best but minimally working alternative - browsersync as standalone tool to manage style injection or full page reload...but with webpack 4 this is broken :cry: 
And I have to stay on the old webpack or switch to the 4th webpack but with a bunch of problems in / or usage of ETWP..
Therefore, I am looking for any people who tell me what happened so that I understand how to fix it, because I do not know the essence of the problem.
Thnks

**Comment by ScriptedAlchemy** [comment]
Waiiit what? You are able to use webpack though, but an older one. 

So my plugin only works with WP4. 

How’s this, do you have a repo with the broken build and I can look at it when I find a little time, get you on webpack 4 and running correctly. I work closely with webpack and various authors- I’m sure we can sort you out
