### ISSUE TITLE
orderWarnings flag removed?

### ISSUE THREAD

**Issue by hedgepigdaniel** [faceyspacey/extract-css-chunks-webpack-plugin#157]
I looks like the `orderWarnings` flag added in https://github.com/faceyspacey/extract-css-chunks-webpack-plugin/pull/108 was removed somewhere between 3.1.3 and 4.0.2.

I'm seeings lots of

```
WARNING in chunk <chunkName> [extract-css-chunks-webpack-plugin]
Conflicting order between:
 * css <modulePath>
 * css <modulePath>
```

https://github.com/webpack-contrib/mini-css-extract-plugin/issues/250#issuecomment-415345126

Was this a deliberate choice?

**Comment by hedgepigdaniel** [comment]
Looks like it happenned in here: https://github.com/faceyspacey/extract-css-chunks-webpack-plugin/pull/136

**Comment by ScriptedAlchemy** [comment]
It should work the same way mini-css extract does. I’ll check their docs and see what needs to be added

**Comment by hedgepigdaniel** [comment]
fixed in https://github.com/faceyspacey/extract-css-chunks-webpack-plugin/pull/158
