### ISSUE TITLE
css-modules failed when using latest version.

### ISSUE THREAD

**Issue by fwh1990** [faceyspacey/extract-css-chunks-webpack-plugin#166]
I am using scss + css-modules, but I can't hot reload the changes of scss files since I upgrade version from 4.3.0 to 4.3.1.

I have to downgrade to 4.3.0 now.

What happened? Any idea?

**Comment by cloudychen** [comment]
me too

**Comment by ScriptedAlchemy** [comment]
Likely from this commit: https://github.com/faceyspacey/extract-css-chunks-webpack-plugin/commit/0ce2460007c4d55da1066bffd3d2b2dace7ed69b

Send me a demo repo and ill have a look

**Comment by fwh1990** [comment]
I debug source code, and find out something may cause error:
```js
function updateCss(el, url) {
  if (!url) {
    url = el.href.split('?')[0];
  }
  ...
}
```

The character `?` may not exist in `el.href`.

**Comment by fwh1990** [comment]
Would you fix this bug at your earliest convenience? I mean, don't use `el.href`, it will return absolute url.

**Comment by ScriptedAlchemy** [comment]
@fwh1990 open a pull request and ill review it. you know what you need better than me

**Comment by ScriptedAlchemy** [comment]
use the `reloadAll` command/option?

**Comment by cloudychen** [comment]
> use the `reloadAll` command/option?

yes

**Comment by silvenon** [comment]
@fwh1990 it would be so great if you could send the PR 😁🙏

**Comment by fwh1990** [comment]
I have tested many versions from 4.3.0~4.5.1, and find out that the bug was fixed by [PR-173](https://github.com/faceyspacey/extract-css-chunks-webpack-plugin/pull/173).

Everybody can upgrade to version `4.5.1`, thanks.

So, I can close this issue now.
