### ISSUE TITLE
Different filename

### ISSUE THREAD

**Issue by tooltonix** [faceyspacey/extract-css-chunks-webpack-plugin#167]
Hello, 

the plugin works very well, even with HMR in the webpack-dev-server. I just have the problem that the CSS file can be generated, but it is included in the HTML via the backend (Symfony) under a different filename. In this case the HMR doesn't work anymore, because the filename is different. Is there a way to work around this problem?

**Comment by ScriptedAlchemy** [comment]
You can control the output file name 

```    new ExtractCssChunks(
        {
          // Options similar to the same options in webpackOptions.output
          // both options are optional
          filename: "[name].css",
          chunkFilename: "[id].css",
          orderWarning: true, // Disable to remove warnings about conflicting order between imports
        }
    ),```
