### ISSUE TITLE
Hot reload doesn't work if webpack is running on different port than HTML page

### ISSUE THREAD

**Issue by glebtv** [faceyspacey/extract-css-chunks-webpack-plugin#170]
https://github.com/faceyspacey/extract-css-chunks-webpack-plugin/blob/master/src/hmr/hotModuleReplacement.js#L183

This checks makes CSS reload not work with webpack-dev-server running on a different port than the page.

Hot reload was working for me on v3.

Is there any way to override this check?

#161 is probably related

**Comment by ScriptedAlchemy** [comment]
Can you open a PR otherwise I’ll check in with webpack as it was added under their recommendations

**Comment by ugin** [comment]
Why was that line added? It breaks HMR on many webpack setups.

```
  // An URL is not an request if

  // 1. It's an absolute url
  if (/^[a-z][a-z0-9+.-]*:/i.test(url)) {
    return false;
  }
```

 It doesn't make sense.

**Comment by ScriptedAlchemy** [comment]
This was a recommendation from webpack based on alternative types of links being added. open a PR and ill address it

**Comment by ScriptedAlchemy** [comment]
thinking on it more, it had to do for scenarios where the URL started with a hash, or basically wasn't a real link that went somewhere. base64 for example.


You got a solution?

**Comment by ugin** [comment]
For me removing this condition `// 1. It's an absolute url` solves my problem. I can make a PR and remove it, is that ok?

**Comment by ScriptedAlchemy** [comment]
please do, I'm at work and legally cannot write the code, but I can merge yours.

Ill also raise this with Webpack directly as I maintain both mini-css and extract css.

**Comment by ScriptedAlchemy** [comment]
@ugin

**Comment by ugin** [comment]
PR created, I didn't bump the version, dunno what the policy is (some OS maintainers didn't like when the version is touched).

**Comment by ScriptedAlchemy** [comment]
No need to bump. We have system automation
