### ISSUE TITLE
HMR not working on IE11 with v4.3.2

### ISSUE THREAD

**Issue by anru** [faceyspacey/extract-css-chunks-webpack-plugin#171]
Exactly same issue as in #138 but for latest version 4.3.2. 

HMR doesn't work due to ES6 syntax in source code.

**Comment by anru** [comment]
Personally, I recommend this utility https://www.npmjs.com/package/es-check for checking final bundle is es5 compatible

**Comment by ScriptedAlchemy** [comment]
Can you pinpoint the problem or open a PR? I dont have time to debug this issue right now but will copy paste a solution if one is provided.

**Comment by ScriptedAlchemy** [comment]
Did a release now, let me know if thats any better. Otherwise, open a PR and fix it

**Comment by anru** [comment]
Ok, I'll check out this

**Comment by ScriptedAlchemy** [comment]
Please do

**Comment by ScriptedAlchemy** [comment]
fix released
