### ISSUE TITLE
bug ie 11 with es6

### ISSUE THREAD

**Issue by maystrenkoYurii** [faceyspacey/extract-css-chunks-webpack-plugin#174]
The library uses a normalize url, but it does not work at the moment in ie11 with es6
![Снимок](https://user-images.githubusercontent.com/23016311/57979345-2387ed00-7a25-11e9-8317-5ae4754408db.PNG)
![Снимок2](https://user-images.githubusercontent.com/23016311/57979346-24208380-7a25-11e9-9cc5-0d20a0ac29b7.PNG)

**Comment by ScriptedAlchemy** [comment]
Open a PR with the version of normalize that’s solves the issue.  I’ll merge it easy

**Comment by ScriptedAlchemy** [comment]
@maystrenkoYurii what version makes it work? I’ll roll back to that one

**Comment by maystrenkoYurii** [comment]
@ScriptedAlchemy ScriptedAlchemy I think you can read here https://github.com/webpack-contrib/mini-css-extract-plugin/issues/385 or replace the normilize-url https://www.npmjs.com/package/normalize-url-es5

**Comment by rexwang** [comment]
Having the same issue. When will it be resolved? @ScriptedAlchemy

**Comment by ScriptedAlchemy** [comment]
I’m at work right now. If any of you open a pull request. I’ll merge and release it in the next 10 seconds

**Comment by ScriptedAlchemy** [comment]
Legal issues prevent me from solving this during office hours and my remote access software seems to be offline at home. So I’m unable to access off-site hardware right now
