### ISSUE TITLE
(4.5.1) SSR: document is not defined (runtime)

### ISSUE THREAD

**Issue by Linzdigr** [faceyspacey/extract-css-chunks-webpack-plugin#175]
I've migrated from webpack 3 to 4 (and switched from ExtractTextPlugin to ExtractCssChunksPlugin) with Vue on SSR and following the related documentation I get in runtime (client request):

> ReferenceError: document is not defined
>      at t.(anonymous function).t.(anonymous function).(anonymous function).o.push.t.(anonymous function).Promise.then.t.(anonymous function) (server-bundle.js:1:432)
>      at Promise (<anonymous>)
>      at Function.module.exports.a.e (server-bundle.js:1:368)
>      at server-bundle.js:1:546528
>      at Promise (<anonymous>)
>      at b (server-bundle.js:1:546502)
>      at /var/www/b4rc/node_modules/vue-router/dist/vue-router.common.js:1776:17
>      at /var/www/b4rc/node_modules/vue-router/dist/vue-router.common.js:1803:66
>      at Array.map (<anonymous>)
>      at /var/www/b4rc/node_modules/vue-router/dist/vue-router.common.js:1803:38

Here is my webpack.module.rules configuration:

```js
{
                test: /\.css$/,
                use: [
                    {
                        loader: ExtractCssChunks.loader,
                        options: {
                            hot: true,
                            reloadAll: true,
                        }
                    },
                    'css-loader'
                ],
            },
            {
                test: /\.scss$/,
                use: [
                    'vue-style-loader',
                    'css-loader',
                    'sass-loader'
                ],
            },
            {
                test: /\.sass$/,
                use: [
                    'vue-style-loader',
                    'css-loader',
                    'sass-loader?indentedSyntax'
                ],
            },
            {
                test: /\.vue$/,
                loader: 'vue-loader',
                options: {
                    extractCSS: true,
                    loaders: {
                        'scss': [
                            'vue-style-loader',
                            'css-loader',
                            'sass-loader'
                        ],
                        'sass': [
                            'vue-style-loader',
                            'css-loader',
                            'sass-loader?indentedSyntax'
                        ]
                    }
                }
            },
```

Using vue-style-loader instead works as expected.

Am I forget something?

**Comment by ScriptedAlchemy** [comment]
Not sure but I guess re-check stuff like our universal demo and see how css is handled on the server. Looks like a browser only event. Not sure it’s related to my plugin though

**Comment by cherryCRazY** [comment]
![image](https://user-images.githubusercontent.com/43639614/61201573-9ba12500-a6ed-11e9-9df7-077debccaeab.png)

**Comment by ScriptedAlchemy** [comment]
You are running the plugin on a server build. Servers have no need for css files to be created. Only client side runtimes. Dont use the plugin on server code :)

**Comment by kevupton** [comment]
Unfortunately, I do have a need for the CSS to be generated on the server. Any ideas on how this can be done? It says that this plugin supports SSR? I am confused,
