### ISSUE TITLE
Unexpected increase of package size after install

### ISSUE THREAD

**Issue by Gobie** [faceyspacey/extract-css-chunks-webpack-plugin#181]
There was ~20 MB increase in install size between https://packagephobia.now.sh/result?p=extract-css-chunks-webpack-plugin@4.5.4 to https://packagephobia.now.sh/result?p=extract-css-chunks-webpack-plugin@4.5.5 created by commit https://github.com/faceyspacey/extract-css-chunks-webpack-plugin/commit/f4d5466bd6ac61b604326e2abd394cdef556f3a4.

Is there a reason, why this is not dev dependency?

**Comment by ScriptedAlchemy** [comment]
Ouch that’s painful. I’ll patch this tomorrow. Thanks for the heads up!
