### ISSUE TITLE
Why is "webpack-external-import" a dependency?

### ISSUE THREAD

**Issue by apnsngr** [faceyspacey/extract-css-chunks-webpack-plugin#194]
Why is "webpack-external-import" a dependency? It does not appear anywhere in the code. The package is GPL 3.0 licensed, so it would be nice if this package was removed or made a "peerDependency" if possible.

_Originally posted by @hamczu in https://github.com/faceyspacey/extract-css-chunks-webpack-plugin/pull/177#issuecomment-507154385_:

Why was "webpack-external-import" added here? I'm asking because:
- it's not used anywhere?
- webpack-external-import has react and redux as peer dependency
- doesn't look stable nor actively developed

**Comment by ScriptedAlchemy** [comment]
extract-css-chunks-webpack-plugin@4.7.2-mit
 MIT version without external-import

**Comment by svewag** [comment]
Is it correct that you removed the dependency? Can you publish it as a regular update?

**Comment by davidragsdale** [comment]
Just to save people clicking on that mailto link above, here's a link to the MIT version in npm. https://www.npmjs.com/package/extract-css-chunks-webpack-plugin/v/4.7.2-mit

**Comment by davidragsdale** [comment]
@ScriptedAlchemy is there any reason to not release this as a regular update? I don't see any usage or peerDependency requirement for this package either.

**Comment by apnsngr** [comment]
@ScriptedAlchemy Thank you for providing a way to use this package without `webpack-external-import`. Unfortunately, I don't use this package directly and I would prefer not to file another issue with `@nuxt-webpack` to ask to for them to use releases with the `-mit` suffix.

Would you be able to provide some background about why this package is a dependency?

**Comment by ScriptedAlchemy** [comment]
Ahhh

**Comment by ScriptedAlchemy** [comment]
Okay I’ll make some adjustments to the main project
