### ISSUE TITLE
html-plugin integration

### ISSUE THREAD

**Issue by cescoferraro** [faceyspacey/extract-css-chunks-webpack-plugin#20]
hey @faceyspacey  I am using 2.0.11
All happening  at https://github.com/cescoferraro/react-boil 
and deployed  https://boil.cescoferraro.xyz/

#### GOAL
Insert all css in a html file using the html-webpack-plugin

#### REASON
In a pwa context, you need to provide a static html file so a service worker can cache it then next time a user hit the website's url, it serves the static html instead of going through the network. 
There is no problem of adding ALL the css because all the files are supposed to be cached by the sw by the time the user visits the website again. The below snippet creates a html page that loads the js chunks in the right order!

    new HtmlWebpackPlugin({
	filename: "html/index.html",
	template:  "./server/index.html",
	showErrors: true,
	chunks:['bootstrap','vendor', 'main'],
	chunksSortMode: (a, b) => { 
	    var order = ['bootstrap','vendor', 'main']; 
	    return order.indexOf(a.names[0]) - order.indexOf(b.names[0]); 
	}
    })

But It I hit boil.cescoferraro.xyz/ with the app properly cached  by chrome and than use the redux-first router link to jump to '/user/345345` I wont see the syles being applied. Css tags wont be inject by the .js files. while Universal component tags that get asynchronously added get inject just fine.
Also if I hit the url straight from `user/234324`, ssr kicks in a deliver the right set of css files.

#### TRIED
 code
```ejs
<% for (var chunk in htmlWebpackPlugin.files.js) { %>
 <%= htmlWebpackPlugin.files.js[chunk] %>
 lsdkmfsdmdfkldsf
<% } %>

<% for (var chunk in htmlWebpackPlugin.files.css) { %>
 <%= htmlWebpackPlugin.files.css[chunk] %>
 lsdkmfsdmdfkldsf
<% } %>

<% for (var chunk in htmlWebpackPlugin.files.chunks) { %>
<%= htmlWebpackPlugin.files.chunks[chunk].entry %>
<% } %>
```

output

```log
 https://boil.cescoferraro.xyz/js/bootstrap_2a26b113ed4fbfd76873.js
 lsdkmfsdmdfkldsf

 https://boil.cescoferraro.xyz/js/vendor.js
 lsdkmfsdmdfkldsf

 https://boil.cescoferraro.xyz/js/main_2a26b113ed4fbfd76873.js
 lsdkmfsdmdfkldsf





https://boil.cescoferraro.xyz/js/bootstrap_2a26b113ed4fbfd76873.js

https://boil.cescoferraro.xyz/js/vendor.js

https://boil.cescoferraro.xyz/js/main_2a26b113ed4fbfd76873.js
```
It seems that the html-plugin does not consider the output of this plugin as being a css file

**Comment by cescoferraro** [comment]
Turns out it was not that hard to write a html-plugin plugin that does that
I hacked https://github.com/GoogleChrome/preload-webpack-plugin just a lil bit

```
'use strict';

const objectAssign = require('object-assign');
const defaultOptions = {
    fileBlacklist: [/\.map/]
};

class PreloadPlugin {
    constructor(options) {
	this.options = objectAssign({}, defaultOptions, options);
    }

    apply(compiler) {
	const options = this.options;
	let filesToInclude = '';
	let extractedChunks = [];
	compiler.plugin('compilation', compilation => {
	    compilation.plugin('html-webpack-plugin-before-html-processing', (htmlPluginData, cb) => {
		let asyncChunksSource = null;
		try {
		    asyncChunksSource = compilation
			.chunks.filter(chunk => !chunk.isInitial())
			.map(chunk => chunk.files);
		} catch (e) {
		    asyncChunksSource = compilation.chunks
			.map(chunk => chunk.files);
		}
		extractedChunks = [].concat.apply([], asyncChunksSource);

		const publicPath = compilation.outputOptions.publicPath || '';

		extractedChunks.filter(entry => {
		    return this.options.fileBlacklist.every(regex => regex.test(entry) === false);
		}).forEach(entry => {
		    entry = `${publicPath}${entry}`;
		    if(entry.endsWith("css"))  {
			    filesToInclude+= `<link rel="stylesheet" type="text/css" href="${entry}">\n`;
		    }
		});
		if (htmlPluginData.html.indexOf('</head>') !== -1) {
		    // If a valid closing </head> is found, update it to include preload/prefetch tags
		    htmlPluginData.html = htmlPluginData.html.replace('</head>', filesToInclude + '</head>');
		} else {
		    // Otherwise assume at least a <body> is present and update it to include a new <head>
		    htmlPluginData.html = htmlPluginData.html.replace('<body>', '<head>' + filesToInclude + '</head><body>');
		}
		cb(null, htmlPluginData);
	    });
	});
    }
}

module.exports = PreloadPlugin;
```

**Comment by faceyspacey** [comment]
Honestly I can't figure out the problem you're having. You wrote:

> you need to provide a static html file

You can do that. 

If the problem has to do with the CSS being injected by CSS, did you see on Friday I released a new extract-css-chunks-webpack-plugin 2.0 along with https://github.com/faceyspacey/babel-plugin-dual-import

Here's the release article:

medium.com/faceyspacey/webpacks-import-will-soon-fetch-js-css-here-s-how-you-do-it-today-4eb5b4929852

It makes it so `import()` fetches both a js and a css file. And then injects both into the page. Maybe that solves your problem. ..But that's a lot of work you did. I would hope these solutions would save you from having to do that.

...im trying to figure out ur problem. I think it revolves around what u said here:

> with the app properly cached by chrome and than use the redux-first router link to jump to '/user/345345I wont see the syles being applied.

I think your problem is that because of how things work client-side you don't end up with something that service works can cache associated with that URL, which is a problem with basically everything that fetches just the bits you need. It seems u need a complete HTML file to cache, which means you're essentially forgoing the benefits of incrementally fetching just the smallest bits you need. Are you now fetching an entire page again? Are you sure you can't just say: "look, the HTML is everything embedded right now"? Of course, if other chunks were already embedded on the page, u'd need a way to say "these chunks aren't vital." 

What are the characteristics of a PWA these days?

**Comment by cescoferraro** [comment]
> It seems u need a complete HTML file to cache, which means you're essentially forgoing the benefits of incrementally fetching just the smallest bits you need. Are you now fetching an entire page again? Are you sure you can't just say: "look, the HTML is everything embedded right now"? Of course, if other chunks were already embedded on the page, u'd need a way to say "these chunks aren't vital."

Yeah! I need a static html file. I am generating it. Meant I not you, sorry
https://boil.cescoferraro.xyz/html/index.html
After the first hit to the website, the sw caches all my webpack assets, so I am not loosing the benefits of incrementally fetching because in the particular context, the client have already fetched it all. Its all of the the browser's app cache. So thats exactly what I am trying to do, provide a html file with everything embedded right away. 

But the new behaviour of the plugin broke my development environment, because now the .js files do not inject the css, so when I navigate though RFR links the css does not get applied. I will try with the previous version and report back. Does 2.0.2 emits no_css files, or do I need 1.0.15 ?

**Comment by cescoferraro** [comment]
@faceyspacey I can confirm it.
I need 1.0.15 for my dev environment to work. I need inject styles. 
Maybe a flag, so you could support people not using babel.

**Comment by faceyspacey** [comment]
It seems the problem isnt that this technique won't work, it's that the technique isn't being applied (you have no css). Cuz style-loader just injects a stylesheet too. 

So if ur not using babel, install the babel plugin and do this:

```js
import importCss from 'babel-plugin-dual-import/importCss'

universal(() => Promise.all(import(/* webpackChunkName: 'Foo' */, './Foo'), importCss('Foo')]), {
   ...etc
})
```

if ur cant do import (i dont know ur setup). use require.ensure, which has a chunkName param. Just make sure u past that same name to `importCss`.

**Comment by faceyspacey** [comment]
but yea, just use the old version if u have to.

**Comment by cescoferraro** [comment]
```diff
modified   app/components/universal.tsx
@@ -2,7 +2,7 @@ import universal from "react-universal-component"
 declare var System: any
 
 export const UniversalComponent = universal(
-    () => System.import(/* webpackChunkName: 'Product' */ "./Product"),
+    () => Promise.all([System.import(/* webpackChunkName: 'Product' */ "./Product")]),
     {
         resolve: () => require.resolveWeak("./Product"),
         chunkName: "Product"
```

```
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of `UniversalComponent`.
    in UniversalComponent (created by Unknown)
    in div (created by Unknown)
    in div (created by Unknown)
    in Unknown (created by Unknown)
    in Unknown (created by AppRouterClass)
    in AppRouterClass (created by Connect(AppRouterClass))
    in Connect(AppRouterClass)
    in AppContainer
    in MuiThemeProvider
    in Provider
    in WithStylesContext
printWarning @ warning.js:36
warning @ warning.js:60
createElement @ ReactElementValidator.js:192
patchedCreateElement @ patch.dev.js:164
createElement @ index.js:171
render @ index.js:157
(anonymous) @ ReactCompositeComponent.js:795
measureLifeCyclePerf @ ReactCompositeComponent.js:75
_renderValidatedComponentWithoutOwnerOrContext @ ReactCompositeComponent.js:794
_renderValidatedComponent @ ReactCompositeComponent.js:821
_updateRenderedComponent @ ReactCompositeComponent.js:745
_performComponentUpdate @ ReactCompositeComponent.js:723
updateComponent @ ReactCompositeComponent.js:644
performUpdateIfNecessary @ ReactCompositeComponent.js:560
performUpdateIfNecessary @ ReactReconciler.js:156
runBatchedUpdates @ ReactUpdates.js:150
perform @ Transaction.js:143
perform @ Transaction.js:143
perform @ ReactUpdates.js:89
flushBatchedUpdates @ ReactUpdates.js:172
closeAll @ Transaction.js:209
perform @ Transaction.js:156
batchedUpdates @ ReactDefaultBatchingStrategy.js:62
enqueueUpdate @ ReactUpdates.js:200
enqueueUpdate @ ReactUpdateQueue.js:24
enqueueSetState @ ReactUpdateQueue.js:218
ReactComponent.setState @ ReactBaseClasses.js:64
UniversalComponent._this.update @ index.js:87
(anonymous) @ index.js:126
warning.js:36 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of `UniversalComponent`.
    in UniversalComponent (created by Unknown)
    in div (created by Unknown)
    in div (created by Unknown)
    in Unknown (created by Unknown)
    in Unknown (created by AppRouterClass)
    in AppRouterClass (created by Connect(AppRouterClass))
    in Connect(AppRouterClass)
    in AppContainer
    in MuiThemeProvider
    in Provider
    in WithStylesContext
printWarning @ warning.js:36
warning @ warning.js:60
createElement @ ReactElementValidator.js:192
patchedCreateElement @ patch.dev.js:164
createElement @ index.js:171
render @ index.js:157
(anonymous) @ ReactCompositeComponent.js:795
measureLifeCyclePerf @ ReactCompositeComponent.js:75
_renderValidatedComponentWithoutOwnerOrContext @ ReactCompositeComponent.js:794
_renderValidatedComponent @ ReactCompositeComponent.js:821
_updateRenderedComponent @ ReactCompositeComponent.js:745
_performComponentUpdate @ ReactCompositeComponent.js:723
updateComponent @ ReactCompositeComponent.js:644
performUpdateIfNecessary @ ReactCompositeComponent.js:560
performUpdateIfNecessary @ ReactReconciler.js:156
runBatchedUpdates @ ReactUpdates.js:150
perform @ Transaction.js:143
perform @ Transaction.js:143
perform @ ReactUpdates.js:89
flushBatchedUpdates @ ReactUpdates.js:172
closeAll @ Transaction.js:209
perform @ Transaction.js:156
batchedUpdates @ ReactDefaultBatchingStrategy.js:62
enqueueUpdate @ ReactUpdates.js:200
enqueueUpdate @ ReactUpdateQueue.js:24
enqueueSetState @ ReactUpdateQueue.js:218
ReactComponent.setState @ ReactBaseClasses.js:64
UniversalComponent._this.update @ index.js:87
(anonymous) @ index.js:128
ReactReconciler.js:62 Uncaught (in promise) TypeError: Cannot read property 'getHostNode' of null
    at Object.getHostNode (ReactReconciler.js:62)
    at ReactCompositeComponentWrapper.getHostNode (ReactCompositeComponent.js:383)
    at Object.getHostNode (ReactReconciler.js:62)
    at ReactCompositeComponentWrapper._updateRenderedComponent (ReactCompositeComponent.js:755)
    at ReactCompositeComponentWrapper._performComponentUpdate (ReactCompositeComponent.js:723)
    at ReactCompositeComponentWrapper.updateComponent (ReactCompositeComponent.js:644)
    at ReactCompositeComponentWrapper.performUpdateIfNecessary (ReactCompositeComponent.js:560)
    at Object.performUpdateIfNecessary (ReactReconciler.js:156)
    at runBatchedUpdates (ReactUpdates.js:150)
    at ReactReconcileTransaction.perform (Transaction.js:143)
```


I just dont get why. I am looking at this https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Promise/all
and cannot find why.

**Comment by faceyspacey** [comment]
my typo:
```js
() => Promise.all([System.import(/* webpackChunkName: 'Product' */ "./Product")]).then(promises => promises[0]),
```

study the babel-plugin brother. not the babel plugin. but the importCss file. what the babel-plugin generates. understand it. the javascript (outside the babel plugin) is stupid easy. just replicate it.

**Comment by cescoferraro** [comment]
I am off work. Havent tried this yet.

**Comment by cescoferraro** [comment]
@faceyspacey got it to work with 2.0.16

```diff
$ git diff package.json
diff --git a/package.json b/package.json
index c19c7731d6d1..edd2006b1600 100644
--- a/package.json
+++ b/package.json
@@ -33,6 +33,7 @@
     "@types/react": "^15.0.35",
     "@types/react-redux": "^4.4.45",
     "awesome-typescript-loader": "^3.2.2",
+    "babel-plugin-dual-import": "^1.1.4",
     "cachedfs": "^0.3.3",
     "classnames": "^2.2.5",
     "compression": "^1.7.0",
@@ -43,7 +44,7 @@
     "enzyme-to-json": "^1.5.1",
     "eslint-config-cesco": "^0.0.2",
     "express": "^4.15.3",
-    "extract-css-chunks-webpack-plugin": "1.0.15",
+    "extract-css-chunks-webpack-plugin": "^2.0.16",
     "extract-text-webpack-plugin": "^2.1.2",
     "faker": "^4.1.0",
     "favicons-webpack-plugin-cesco": "^0.0.6",
```

but now I need to to supply window.__CSS_CHUNKS__. 
Which is  easy on the server  with cssHash ans cssHashRaw.
But on the PWA context, my lil plugin does not work anymore as expected.
Funny thing is that I saw a warning in dev when not supĺying __CSS_CHUNKS__, but cannot see the same warning in production. Although it seems all its missing for it to work.

**Comment by cescoferraro** [comment]
i have messed with this a bit 
https://github.com/cescoferraro/react-boil/commit/6b619b3ca37f33fb8f666ceb4b714664819697fb#diff-b90c2f45a80c0e59e9507ed316da8277
```js
  apply(compiler) {
    let filesToInclude = '';
    let extractedChunks = [];
    compiler.plugin('compilation', compilation => {
      compilation.plugin(
        'html-webpack-plugin-before-html-processing',
        (htmlPluginData, cb) => {
          extractedChunks = [...compilation.chunks.map(chunk => chunk.files)];
          const publicPath = compilation.outputOptions.publicPath || '';
          filesToInclude =
            ' <script> window.__CSS_CHUNKS__ = ' +
            serialize(
              createCssHash({
                publicPath,
                assetsByChunkName: extractedChunks
              })
            ) +
            '</script> ';
```

I get
 window.__CSS_CHUNKS__ = {"0":"https:\u002F\u002Fboil.cescoferraro.xyz\u002Fcss\u002Fuser_fd4a6d4578aa8bdd4f16.css","2":"https:\u002F\u002Fboil.cescoferraro.xyz\u002Fcss\u002Fmain_fd4a6d4578aa8bdd4f16.css"}


But I should be seeing something similar to what I see on my dev environment.
window.__CSS_CHUNKS__ = {"user":"http:\u002F\u002Flocalhost:5000\u002Fuser.6421f6f8e5f98d6c2d7f907bc302e3ff.css","main":"http:\u002F\u002Flocalhost:5000\u002Fmain.db654ab88cc2d72cc802504720f92505.css"}

**Comment by faceyspacey** [comment]
The warning goes away in production because the comments are only shown when process.env.NODE_ENV === 'development' which is stripped in production.

**Comment by faceyspacey** [comment]
Honestly, regarding using html-webpack-plugin, these tools are for when you want to move beyond the automation of that plugin which automatically injects things for you. You really don't want to be using that plugin anymore if you've moved to the level where you're using these tools. So now you're expending energy making flexible tools work in what is supposed to be an easier environment, but like similar to frameworks, becomes the worse option once you want customizability.

**Comment by faceyspacey** [comment]
your extracted chunks aren't being named. That could happen for several reasons. For one add this to your config:

```js
output: {
    chunkFilename: '[name].js',
```

Named chunks like `main` should already be named, so it appears that maybe in the webpack plugin hook they have yet to be named. 

Either way, the Universal toolset doesn't require them to be named. It can work when they are still `0.js`, etc.

**Comment by faceyspacey** [comment]
I'd just get away from that html plugin man, and just do things the recommended way which affords you way more flexibility.

**Comment by cescoferraro** [comment]
@faceyspacey it all works man! Thanks for everything
The html plugin is for the PWA context! I need to generate a html file somehow!

**Comment by cescoferraro** [comment]
@faceyspacey  I tried the config.output.chunkFIlename option but no luck.
I will try to hack the object to infer the obj prop from the file name, so I can have a working branch.
But I think this is something to do with how typescrict does not handles all the new import spec just yet.

**Comment by cescoferraro** [comment]
got it

```js
          const hashes = createCssHash({
            publicPath,
            assetsByChunkName: extractedChunks
          });
          Object.keys(hashes).forEach(function(key) {
            const tt = hashes[key].split('_')[0].split('/').reverse()[0];
            hashes[tt] = hashes[key];
            delete hashes[key];
          });
          filesToInclude =
            ' <script> window.__CSS_CHUNKS__ = ' +
            serialize(hashes) +
            '</script> ';
```

**Comment by teddybradford** [comment]
I ran into this same issue. What's the proper way to have the CSS chunks injected into the head of index.html?

**Comment by faceyspacey** [comment]
This isn't my forte, as I don't use HtmlWebpackPlugin, but basically these tools are intended for pretty manual setups that wouldn't use that. So the recommended way is to take full control of the html wrapper code and generate it yourself. I'm sorry to say. 

However, @cescoferraro 's solution perhaps could be formalized more and become the recommended solution??

**Comment by mike1808** [comment]
I'm interested in this integration too since I don't use SSR and cannot use your other plugins. So, I need to add this css chunk paths to window using HtmlPlugin 
```js
window.__CSS_CHUNKS__ = {
    Foo: '/static/Foo.css',
    'base/Page1': '/static/base/Page1.css',
    'base/Page2': '/static/base/Page2.css',
  }
```

**Comment by mike1808** [comment]
@faceyspacey so, I figured out how to include css chunks into HTML file.

I wrote small plugin for html plugin based on function from webpack-flush-chunks cssChunckHash function:

```js
/* eslint-disable */

function CssChunkHash(options) {
}

CssChunkHash.prototype.createCssHash = function ({ assetsByChunkName, publicPath }) {
    return Object.keys(assetsByChunkName).reduce((hash, name) => {
        if (!assetsByChunkName[name] || !assetsByChunkName[name].find) return hash;
        const file = assetsByChunkName[name].find(file => file.endsWith('.css'));
        if (file) hash[name] = `${publicPath}${file}`;
        return hash;
    }, {});
};


CssChunkHash.prototype.apply = function (compiler) {
    const self = this;
    compiler.plugin('compilation', function (compilation) {
        compilation.plugin('html-webpack-plugin-before-html-generation', function (htmlPluginData, callback) {
            const webpack = compilation.getStats().toJson();
            const cssHash = self.createCssHash(webpack);
            htmlPluginData.assets.cssHash = cssHash;
            callback(null, htmlPluginData);
        });
    });
};

module.exports = CssChunkHash;
```

Then, just include it in webpack config and use the following code in your html template (ejs in my case):

```ejs
<script type="text/javascript">
    window.__CSS_CHUNKS__ = JSON.parse('<%= JSON.stringify(htmlWebpackPlugin.files.cssHash) %>')
</script>
```

**Comment by faceyspacey** [comment]
That is very clean! ...you should publish it and add a PR to this repo with a link to it.
