### ISSUE TITLE
Documentation is confusing

### ISSUE THREAD

**Issue by SystemParadox** [faceyspacey/extract-css-chunks-webpack-plugin#203]
This plugin looks like it might be really amazing, but I am finding the documentation very confusing. It's got lots of webpack config examples, but no examples of other files (e.g. JS, HTML). There are a few things that I cannot figure out:

1. Is this plugin supposed to insert the styles into the HTML automatically like `style-loader` does? The documentation makes it seems like it's supposed to, but from testing it doesn't appear to.
2. Should we be using `style-loader` at all with this plugin? I think the answer is no?
3. How do you avoid a FOUC when using this plugin? Can we just add a `<link rel='stylesheet' href='/build/main.css' />`? Or do we have to add this in some circumstances but not others?
4. Is HMR enabled by default or do I have to specify `options: { hmr: true }` to enable it?
5. Is it necessary to configure this plugin differently between development and production or is that taken care of automatically?

From what I can work out it seems like you just add `<link rel='stylesheet' href='/build/main.css' />` to the HTML, enable HMR for this plugin by passing `options: { hmr: NODE_ENV == 'development' }` and then everything works correctly in both development and production. If that's so, this is absolutely fantastic! But you should really update the documentation to make this much more obvious. Currently it makes it look really complicated like you might still have to juggle multiple configs and mess with `style-loader` and maybe add `<link>` sometimes but not others. If it's really as straightforward as I'm hoping, the documentation should be really cut down and start with the minimum working development/production example with HMR (but include HTML and JS code in the example).

Thanks.

**Comment by ScriptedAlchemy** [comment]
the docs are the same as mini-css, if you want style injections inline or want no FOUC then you need something like html webpack plugin.

**Comment by SystemParadox** [comment]
> the docs are the same as mini-css

That doesn't answer any of my questions. The mini-css documentation is unclear as well.

> if you want style injections inline or want no FOUC then you need something like html webpack plugin.

Perhaps I was unclear. I didn't mean changing the initial HTML file, I meant actually loading the CSS at any point. At the moment it seems like this plugin doesn't do anything to actually load the CSS files it generates, but because of the unclear documentation I'm still not sure if this is intended behaviour or not.

**Comment by VitaliiB** [comment]
> 1. Is this plugin supposed to insert the styles into the HTML automatically like `style-loader` does? The documentation makes it seems like it's supposed to, but from testing it doesn't appear to.

As far as i understand, it's up to you how and where you insert links to generated CSS files. 

Also, when output filenames are dynamically generated, like this:
```
    new ExtractCssChunks({
      // Options similar to the same options in webpackOptions.output
      // both options are optional
      filename: devMode ? '[name].css' : '[name].[hash].css',
      chunkFilename: devMode ? '[id].css' : '[id].[hash].css',
    }),
```
you should use plugins such as `assets-webpack-plugin` or `webpack-assets-manifest` to be able to read generated filenames from somewhere.

Here is an example of project using `mini-css-extract-plugin` (the same as `extract-css-chunks-webpack-plugin`).

https://github.com/wellyshen/react-cool-starter/blob/master/tools/webpack/config.babel.js
https://github.com/wellyshen/react-cool-starter/blob/master/src/server.tsx

Concerning dynamically generated CSS names, maybe that example uses `loadable-components` to extract only required links for every route, i couldn't figure that out for now.

**Comment by ScriptedAlchemy** [comment]
Open a PR

**Comment by Airkro** [comment]
Since `mini-css-extract-plugin` support `HMR` too, I can't find the difference between them. It should be clear in Documentation too.

**Comment by ScriptedAlchemy** [comment]
This project become mini-css. I’m the one who wrote all the support

**Comment by Airkro** [comment]
Sorry, but what `become` mean?

**Comment by ScriptedAlchemy** [comment]
I maintain both. Extract css chunks merged into mini css over a year ago. You can use either one. Modern features come to extract css before they go to mini css. Other than that. They remain the same internally because I pull request code from here to there. Feel free to use either, they look the same because I code new features on this one. Then merge them to mini css :)
