### ISSUE TITLE
How to serve the respective CSS chunk files when the JS chunks loads?

### ISSUE THREAD

**Issue by ankeetmaini** [faceyspacey/extract-css-chunks-webpack-plugin#21]
I am trying to use this, and while building although the CSS chunks are emitted, but I don't see the CSS files loaded when I load the JS chunks.

I've created a sample app [(github repo, you can `npm install` and `npm start`)](https://github.com/ankeetmaini/css-chunks-sample-app) with three routes `/a`, `/b` and  `/c` whose bundles are loaded when I enter that route, but I don't see the CSS bundles getting loaded in the latest version 2.0.4. Earlier also the bundles weren't loaded but style tags were getting added.

Not sure what's causing this. Can you help me in pointing how to serve the CSS bundles on demand like it happens for JS chunks?

```
stylesheets/app-global.css    1.52 kB       4  [emitted]         app
stylesheets/c-modules.css  211 bytes       0  [emitted]         c
stylesheets/b-modules.css  211 bytes       1  [emitted]         b
stylesheets/a-modules.css  212 bytes       2  [emitted]         a
```

but none of the chunk CSS files get added to my HTML.

```html
<link href="/assets/stylesheets/app-global.css" rel="stylesheet">
```
`a-modules.css`, `b-modules.css` or `c-modules.css` doesn't load when I navigate to the respective routes

**Comment by faceyspacey** [comment]
This is to be used with `import()` not multiple bundles/entry points:

https://medium.com/faceyspacey/webpacks-import-will-soon-fetch-js-css-here-s-how-you-do-it-today-4eb5b4929852

use `babel-plugin-dual-import` + `import()` to achieve what you're doing. Good luck.

**Comment by faceyspacey** [comment]
here's how u do it instead by the way:

**old way:**
```js
import a from 'bundle-loader?lazy&name=a!./components/A';
import b from 'bundle-loader?lazy&name=b!./components/B';
import c from 'bundle-loader?lazy&name=c!./components/C';
```

**new way:**
```js
const a = () => import('./components/A')
const b = () => import('./components/A')
const c = () => import('./components/A')
```

So yea, i used to do it with bundle-loader and lazy too. But now `import()` is the standard, and there are LOTS of things u can do with it. Like my dual-import babel plugin which will fetch BOTH a js AND a css file. U can also universally render with components like https://github.com/faceyspacey/react-universal-component and serve only the used/rendered assets from the server via: https://github.com/faceyspacey/webpack-flush-chunks

So those are some reasons why u wanna upgrade to the latest Webpack tech. Hope this helps.

**Comment by ankeetmaini** [comment]
Thanks so much! Will try this out!

**Comment by faceyspacey** [comment]
Make sure to use this plugin once. The point is it will pick up all dynamic imports. Make sure you are using webpack-flush-chunks linked from the readme if you want universal rendering.
