### ISSUE TITLE
hot module replacement dont work with absolute publicPath

### ISSUE THREAD

**Issue by lutzk** [faceyspacey/extract-css-chunks-webpack-plugin#25]
when hot updating the plugin takes the current `protocol + host + port + publicPath + outputFilename`

```
https://github.com/faceyspacey/extract-css-chunks-webpack-plugin/blob/master/hotModuleReplacement.js#L3
https://github.com/faceyspacey/extract-css-chunks-webpack-plugin/blob/master/hotModuleReplacement.js#L4
```

so the check in `https://github.com/faceyspacey/extract-css-chunks-webpack-plugin/blob/master/hotModuleReplacement.js#L13`
`oldChunk === newChunk` is always false:

```
oldChunk = http://localhost:3011/dist/assets/Login
newChunk = http://localhost:3010http://localhost:3011/dist/assets/Login
```

when i comment  out the `origin` it works

there could be a check for if the `publicPath` is an absolute one and just add the `origin` if its not 

should i send i pr for this?

**Comment by faceyspacey** [comment]
most definitely. would appreciate the PR. thanks!

**Comment by faceyspacey** [comment]
This PR from @phyllisstein may do the trick:

https://github.com/faceyspacey/extract-css-chunks-webpack-plugin/pull/24

it just came in. I'll be reviewing these Issues fully on Monday.

**Comment by lutzk** [comment]
i checked https://github.com/faceyspacey/extract-css-chunks-webpack-plugin/pull/24
i havent tested but i think it wont fix that issue here as 
[](https://github.com/faceyspacey/extract-css-chunks-webpack-plugin/pull/24/files#diff-cde6d9f26a4905133b8b97413ed0514eL4)
the `newHref`  is still `newHref = origin + publicPath + outputFilename`

**Comment by phyllisstein** [comment]
If I understand the issue correctly, I think this commit to #24 should resolve it: <https://github.com/faceyspacey/extract-css-chunks-webpack-plugin/pull/24/commits/6ed9ed1ac2c393d4f0bbd7a274c770a22fbe4b4a>. The `URL` constructor accepts a base URL as its second parameter; the change assumes that any `publicPath` that includes a protocol string is a valid base URL and passes it to the `new URL`, or uses `window.location` as the base if it's missing.

**Comment by lutzk** [comment]
yes looks like it would fix my issue
but looks like if `publicPath.match(/https?:/g)` is false you lost the `publicPath` ?
i left a comment at https://github.com/faceyspacey/extract-css-chunks-webpack-plugin/pull/24/commits/c86dfac9e31dfaba00611e5bae362fe7633fc593 
thank you

**Comment by faceyspacey** [comment]
@phyllisstein PR fixing this and related issues has been merged. `yarn upgrade extract-css-chunks-webpack-plugin`. Thanks again @phyllisstein !!
