### ISSUE TITLE
Throws when compiling (recording phase): "Path variable [name] not implemented in this context"

### ISSUE THREAD

**Issue by swernerx** [faceyspacey/extract-css-chunks-webpack-plugin#26]
I tried upgrading by code from 1.x to 2.x. Unfortunately it does not work that well out of the box.

Stack Trace:

<details>
<code>
/Users/Sebastian/Workspace/sebastian-software/edge-builder/node_modules/webpack/lib/TemplatedPathPlugin.js:71
                .replace(REGEXP_NAME, getReplacer(chunkName))
   ^
Error: Path variable [name] not implemented in this context: [name].css
    at /Users/Sebastian/Workspace/sebastian-software/edge-builder/node_modules/webpack/lib/TemplatedPathPlugin.js:48:26
    at String.replace (<anonymous>)
    at MainTemplate.replacePathVariables (/Users/Sebastian/Workspace/sebastian-software/edge-builder/node_modules/webpack/lib/TemplatedPathPlugin.js:71:4)
    at MainTemplate.applyPluginsWaterfall (/Users/Sebastian/Workspace/sebastian-software/edge-builder/node_modules/tapable/lib/Tapable.js:91:24)
    at Compilation.getPath (/Users/Sebastian/Workspace/sebastian-software/edge-builder/node_modules/webpack/lib/Compilation.js:1283:28)
    at /Users/Sebastian/Workspace/sebastian-software/edge-builder/node_modules/extract-css-chunks-webpack-plugin/index.js:360:22
    at getFile (/Users/Sebastian/Workspace/sebastian-software/edge-builder/node_modules/extract-css-chunks-webpack-plugin/index.js:355:49)
    at ExtractTextPlugin.<anonymous> (/Users/Sebastian/Workspace/sebastian-software/edge-builder/node_modules/extract-css-chunks-webpack-plugin/index.js:338:17)
    at Array.forEach (native)
    at ExtractTextPlugin.<anonymous> (/Users/Sebastian/Workspace/sebastian-software/edge-builder/node_modules/extract-css-chunks-webpack-plugin/index.js:326:20)
    at Compilation.applyPluginsAsyncSeries (/Users/Sebastian/Workspace/sebastian-software/edge-builder/node_modules/tapable/lib/Tapable.js:142:13)
    at sealPart2 (/Users/Sebastian/Workspace/sebastian-software/edge-builder/node_modules/webpack/lib/Compilation.js:636:9)
    at next (/Users/Sebastian/Workspace/sebastian-software/edge-builder/node_modules/tapable/lib/Tapable.js:138:11)
    at Compilation.compilation.plugin (/Users/Sebastian/Workspace/sebastian-software/edge-builder/src/plugins/VerboseProgress.js:1:2270)
    at next (/Users/Sebastian/Workspace/sebastian-software/edge-builder/node_modules/tapable/lib/Tapable.js:140:14)
    at ExtractTextPlugin.<anonymous> (/Users/Sebastian/Workspace/sebastian-software/edge-builder/node_modules/extract-css-chunks-webpack-plugin/index.js:301:5)
    at /Users/Sebastian/Workspace/sebastian-software/edge-builder/node_modules/async/dist/async.js:421:16
    at iteratorCallback (/Users/Sebastian/Workspace/sebastian-software/edge-builder/node_modules/async/dist/async.js:998:13)
    at /Users/Sebastian/Workspace/sebastian-software/edge-builder/node_modules/async/dist/async.js:906:16
    at /Users/Sebastian/Workspace/sebastian-software/edge-builder/node_modules/extract-css-chunks-webpack-plugin/index.js:284:6
    at /Users/Sebastian/Workspace/sebastian-software/edge-builder/node_modules/async/dist/async.js:421:16
    at iteratorCallback (/Users/Sebastian/Workspace/sebastian-software/edge-builder/node_modules/async/dist/async.js:998:13)
    at /Users/Sebastian/Workspace/sebastian-software/edge-builder/node_modules/async/dist/async.js:906:16
    at /Users/Sebastian/Workspace/sebastian-software/edge-builder/node_modules/extract-css-chunks-webpack-plugin/index.js:274:9
    at rebuilding.forEach.cb (/Users/Sebastian/Workspace/sebastian-software/edge-builder/node_modules/webpack/lib/Compilation.js:504:29)
    at Array.forEach (native)
    at callback (/Users/Sebastian/Workspace/sebastian-software/edge-builder/node_modules/webpack/lib/Compilation.js:504:15)
    at processModuleDependencies (/Users/Sebastian/Workspace/sebastian-software/edge-builder/node_modules/webpack/lib/Compilation.js:523:5)
</code>
</details>

My configuration is pretty straightforward for the plugin:

```
      isClient ? new ExtractCssChunks({
        filename: isDevelopment ? "[name].css" : "[name].[contenthash:base62:8].css"
      }) : null,
```

Do you have any idea why this is happening?

**Comment by swernerx** [comment]
The code in `webpack/lib/TemplatedPathPlugin.js` looks pretty simple. For replacing `[name]` it just looks for `chunk.name` or `chunk.id`. It seems like there is at least one chunk in the current compilation which does not offer such a value.

**Comment by swernerx** [comment]
When modifying the code inside this library to:

```
function getPath(compilation, source, chunk) {
	return function(format) {
    console.log("Chunk:",chunk)
		return compilation.getPath(format, {
			chunk: chunk
		}).replace(/\[(?:(\w+):)?contenthash(?::([a-z]+\d*))?(?::(\d+))?\]/ig, function() {
			return loaderUtils.getHashDigest(source, arguments[1], arguments[2], parseInt(arguments[3], 10));
		});
	}
}
```

I can see that immediately before it throws the chunk printed to the console is offering neither a `chunk.id` or `chunk.name`:

```Chunk {
  id: null,
  ids: null,
  debugId: 1008,
  name: null,
  _modules: 
   SortableSet {
```

**Comment by swernerx** [comment]
Changing the code in `getPath` to this fixes compilation:

```
function getPath(compilation, source, chunk) {
	return function(format) {
    if (chunk.name == null && chunk.id == null) {
      console.log("Missing name/id for: ", chunk.debugId)
      chunk.name = "debugId-" + chunk.debugId
    }
		return compilation.getPath(format, {
			chunk: chunk
		}).replace(/\[(?:(\w+):)?contenthash(?::([a-z]+\d*))?(?::(\d+))?\]/ig, function() {
			return loaderUtils.getHashDigest(source, arguments[1], arguments[2], parseInt(arguments[3], 10));
		});
	}
}
```

**Comment by swernerx** [comment]
<img width="725" alt="bildschirmfoto 2017-07-17 um 19 10 23" src="https://user-images.githubusercontent.com/145201/28280318-ac5dcbb2-6b23-11e7-9661-70e06b75d59c.png">

That's the output I see in the Chrome developer tools right now.

**Comment by faceyspacey** [comment]
thanks for this. I'm just getting started for the week. I'll look into it.

**Comment by faceyspacey** [comment]
I'm working on getting to the bottom of the issue for why there is no `chunk.name` or `chunk.id`.

...Regarding the latest issue with `__CSS_CHUNKS__` being empty, it is likely related to react-universal-component or webpack-flush-chunks.

Here's what we need to look at to see where the problem lies?

- What does the compiled code for your call to `import()` look like?
- what is the return of `flushChunkNames()`? 
- if you log `stats.assetsByChunkName`, what do you see? 
- have you upgraded both `webpack-flush-chunks` and `react-universal-component`?
- can you install this simple plugin during development to see what files are created: https://github.com/gajus/write-file-webpack-plugin

My guess is either the files aren't being created or `flushChunkNames()` is returning an empty array (which can happen for several reasons). If the files aren't being created, perhaps it has to do with the `chunk.id/name` not being available, in which case there is no chunk in the stats, which the rest of the system depends on.

**Comment by faceyspacey** [comment]
Also what webpack version are you using?

**Comment by faceyspacey** [comment]
Ok. i've tried Webpack 3.1, 3.3 and 2.6.1, each with a filename specified as you have (both with and without the `contenthash`), and it still works for me.

I've seen this issue (`Path variable [name] not implemented in this context`) before while working on this. Are you sure you're upgraded to 2.0.4, or did you upgrade to the `next` dist-tag? The next dist-tag is old at 2.0.0 and had issues like this one. If you do `yarn upgrade extract-css-chunks-webpack-plugin` you'll be using 2.0.5 (which i just published with upgraded deps in case that was your issue). 

I can help you solve it, but I'll need a minimal repro to look at.

**Comment by psachs21** [comment]
I've also run into this situation. I was replacing an existing ExtractTextPlugin with this plugin and it threw the same exception (webpack 3.2.0). Unfortunately, my config is relatively complicated so making a minimal repro was not trivial. Will try when I get some time.

**Comment by faceyspacey** [comment]
@psachs21 i might be able to find the issue with very little info. Can you paste the following:

- webpack-flush-chunks usage
- react-universal-component or `import()` usage
- transpiled result of `import()` *-- this likely has the clue*
- how `ExtractCssChunks` is used as a loader

**Comment by swernerx** [comment]
I figure it's probably related to the babel plugin not correctly working. I was in some kind of debugging session yesterday with that issue and will continue now :)

**Comment by swernerx** [comment]
Webpack 3.3.0
Dual Import 1.1.1
webpack-flush-chunks 1.1.10
react-universal-component 1.5.0

**Comment by swernerx** [comment]
I added a debug statement in the "constructor" of the universal component:

```js
function universal(component) {
  var opts = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : {};

  console.log("OPTS:",opts)
```

Output:

```
OPTS: { resolve: [Function: resolve], chunkName: 'views/Home/Home' }
OPTS: { resolve: [Function: resolve],
  chunkName: 'views/Missing/Missing' }
```

This feels like if the plugin is not running correctly... right?

**Comment by swernerx** [comment]
This is the output of 

```js
const chunkNames = flushChunkNames()
const { js, styles, cssHash } = flushChunks(clientStats, { chunkNames })

console.log("Rendered Chunk Names:", chunkNames)
```

```
Rendered Chunk Names: [ 'views/Home/Home', 'views/Missing/Missing' ]
```

**Comment by faceyspacey** [comment]
someone else actually just had the same issue and got it working (also just responded a few moments ago):

https://github.com/faceyspacey/flush-chunks-boilerplate-webpack/issues/1#issuecomment-315978161

...it doesn't change the options. It transforms the first argument to `universal`. That's what we need to look at.

**Comment by faceyspacey** [comment]
Your chunkname should be `Home` and `Missing` respectively. It's just the filename unless you're using dynamic requires. When you look at the transpiled code, you will likely see `/* webpackChunkName: 'Home' */`

**Comment by swernerx** [comment]
This is my output of adding both, component and options debug messages to `universal`:

```
function universal(component) {
  var opts = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : {};

  console.log("IS UNIVERSAL:",component)
  console.log("OPTS:",opts)
```

```
IS UNIVERSAL: ()=>Promise.resolve().then(()=>__webpack_require__(83))
OPTS: { resolve: [Function: resolve], chunkName: 'views/Home/Home' }
IS UNIVERSAL: ()=>Promise.resolve().then(()=>__webpack_require__(84))
OPTS: { resolve: [Function: resolve],
```

**Comment by faceyspacey** [comment]
...you know we need to do: edit `node_modules/babel-loader` to log what it transforms before Webpack transforms it again. 

..And Actually I was wrong--you have the correct chunknames. It does keep the dirs, even for non-dynamic imports.

**Comment by faceyspacey** [comment]
also post the output of `clientStats.assetsByChunkName`. ..all signs are pointing to the chunks not being created since `flushChunkNames` is working.

**Comment by faceyspacey** [comment]
...if you're using a babel feature to strip comments, you will have this issue, as it will remove the magic comment:

https://github.com/faceyspacey/babel-plugin-dual-import/issues/1#issuecomment-313891179

That could be it.

**Comment by swernerx** [comment]
Oh!

**Comment by faceyspacey** [comment]
...in your case, the babel plugin isn't being applied at all. There should be at least `Promise.all` appearing in the webpack-transformed output. 

do you have it set as just the following in your .babelrc:

```
{
  "presets": [whatever you usually have],
  "plugins": ["dual-import"]
}
``` 

If you're editing the babelrc in webpack config, there's probably a change that needs to be made there.

**Comment by swernerx** [comment]
The babel plugin is actually executed... I see logs from there.

**Comment by swernerx** [comment]
This is how it looks like for me:

```
{
  "env": {
    "edge-development-client": {
      "presets": [
        [ "edge", { "target": "browser" }]
      ],
      "plugins": [
        "dual-import"
      ]
    },
...
```

**Comment by faceyspacey** [comment]
That's correct...and you don't overrwrite your babel config within your webpack config?

The final transformed output is showing no signs of the dual-import plugin.

**Comment by swernerx** [comment]
No. Webpack explicitely uses babelRC

**Comment by swernerx** [comment]
Probably it's some issue with my babel-preset-edge together with "dual-import"

**Comment by faceyspacey** [comment]
yea. try:

{
  "presets": ["es2015", "react", "stage-2"],

**Comment by faceyspacey** [comment]
https://github.com/sebastian-software/babel-preset-edge/blob/master/src/index.js#L282

**Comment by faceyspacey** [comment]
you want `dynamicImportWebpack` not `dynamicImportNode`

**Comment by faceyspacey** [comment]
although with the latest webpack you don't need it at all.

**Comment by swernerx** [comment]
That should only be active when publishing libraries... mainly to convince Rollup for correctly bundling. Shouldn't be active in these cases.

**Comment by faceyspacey** [comment]
this is exactly what ur source looks like:

https://github.com/airbnb/babel-plugin-dynamic-import-node/blob/master/src/index.js#L8

**Comment by faceyspacey** [comment]
that's exactly what transformed to tho:

```js
()=>Promise.resolve().then(()=>__webpack_require__(83))
```

**Comment by swernerx** [comment]
Mhh, maybe that's a bug... will try tracking that down.

Also, when using this config:

```
{
  "env": {
    "edge-development-client": {
      "presets": [ "env", "react" ],
      "plugins": [
        "syntax-dynamic-import",
        "transform-object-rest-spread",
        "transform-class-properties",
        "dual-import"
      ]
    },

    "edge-development-server": {
      "presets": [ "env", "react" ],
      "plugins": [
        "syntax-dynamic-import",
        "transform-object-rest-spread",
        "transform-class-properties",
        "dual-import"
      ]
    },
```

it works fine!

BTW: It seems that CSS HMR does not work...

**Comment by swernerx** [comment]
I'll check my Babel config to do things correctly.

**Comment by faceyspacey** [comment]
there were some updates to ECCWP earlier today. make sure ur upgraded to 2.0.6

**Comment by swernerx** [comment]
Regarding these missing chunk names/ids: I figure it would be useful to throw instead of producing a breaking build.

```js
function getPath(compilation, source, chunk) {
	return function(format) {
		if (chunk.name == null && chunk.id == null) {
			throw new Error("Missing chunk id/name! Can't proceed without. Please check your setup of babel-plugin-dual-import!")
		}
		return compilation.getPath(format, {
			chunk: chunk
		}).replace(/\[(?:(\w+):)?contenthash(?::([a-z]+\d*))?(?::(\d+))?\]/ig, function() {
			return loaderUtils.getHashDigest(source, arguments[1], arguments[2], parseInt(arguments[3], 10));
		});
	}
}

```

Pseudo pull-request ;)

**Comment by swernerx** [comment]
I somehow thought that I should be able to remove the second "opts" argument from "universal()" once everything it set-upped correctly. But when doing this everything still works but the previous line where I debug rendered chunk names (server side) only mentions `[ "default" ]` instead of `[ 'views/Home/Home', 'views/Missing/Missing' ]`.

**Comment by swernerx** [comment]
HMR still does not work as it seems for CSS - that's the output of HMR on the client:

```
[HMR] connected
client.js:199 [HMR] bundle rebuilding
client.js:207 [HMR] bundle rebuilt in 493ms
process-update.js:27 [HMR] Checking for updates on the server...
process-update.js:98 [HMR] Nothing hot updated.
process-update.js:107 [HMR] App is up to date.
```

**Comment by faceyspacey** [comment]
yea, you need to provide the options still. react-loadable replaces the need for all that. 

...truth is, another plugin that does what dual-import does and what react-loadable's babel plugin does is coming out any day now:

https://github.com/faceyspacey/babel-plugin-universal-import

and a few other things. FYI, if you get what you have working, the transition will be seamless.

...dont try to use that plugin. it requires the @next dist-tag of react-universal-component. u could, but i gotta revisit before i launch. it's been sitting on the vine for a while. there's actually a [PR](https://github.com/webpack/webpack/pull/5235) to webpack i'm working on pushing through to make dynamic imports work universally. things are about to come together nicely.

**Comment by swernerx** [comment]
I am watching this PR, too :)

**Comment by faceyspacey** [comment]
as far as the css goes, i can't quite call it. ..if u use the write-file webpack plugin do you instantly see your changes in the css chunk on your hard drive?

**Comment by swernerx** [comment]
I don't use that plugin right now... I'll just discovered it in your code. I'll try to bake it into edge-builder later in the day.

**Comment by faceyspacey** [comment]
i only toggle it on/off when i'm debugging things like this and want to see what otherwise would be in the webpack-dev/hot-middleware. 

...there's 2 places HMR could go wrong:
- if the update did take place on the server, HMR on the client fails to replace the sheets
- the chunks aren't being re-compiled

I think you're in the second group since the HMR logs are saying there is nothing new. I haven't seen that. It seems as if the css files being watched are triggering updates, but aren't in fact imported by a component file.

**Comment by faceyspacey** [comment]
you should see this:

```js
client.js:67 [HMR] connected
client.js:199 [HMR] bundle rebuilding
client.js:207 [HMR] bundle rebuilt in 225ms
process-update.js:27 [HMR] Checking for updates on the server...
process-update.js:100 [HMR] Updated modules:
process-update.js:102 [HMR]  - ./node_modules/extract-css-chunks-webpack-plugin/hotModuleReplacement.js
process-update.js:102 [HMR]  - ./src/css/Example.css
process-update.js:107 [HMR] App is up to date.
hotModuleReplacement.js:30 [HMR] Reload css:  http://localhost:3000/static/Example.css?1500367058037
```

**Comment by swernerx** [comment]
Do I have to implement something specific to include the "hotModuleReplacement" from "extract-css-chunks-webpack-plugin"?

**Comment by faceyspacey** [comment]
No the loader will append it to each module

**Comment by swernerx** [comment]
I think we can close the issue as the original problem is gone now.

**Comment by faceyspacey** [comment]
By the way, I found more stuff related to this issue: basically the `babel-plugin-dual-import` only works with `flushChunkNames()`. I forgot to document that. But that's not what triggers this error:

`Error: Path variable [name] not implemented in this context: [name].css`

What triggers it is when the dual-import plugin isn't applied, in which case there is no name for chunks. And the current incarnation of this webpack-plugin only works with chunkNames. 

I'm plan on making it work with the `flushModuleIds` as well, as it used to, which if it does will at least not break your build even if the dual-import plugin isn't applied or in use.

**Comment by faceyspacey** [comment]
Ok, I've fixed it. You can do `yarn upgrade extract-css-chunks-webpack-plugin`.

It will no longer produce errors when chunk names are not used. Which means when the babel plugin isn't working, your app won't break. That may in fact be less helpful, since you will have less clues that something went wrong. But this prepares us for a potential moduleId based future in terms of the entire setup.

I've also updated this readme and the babel plugin's readme with better comprehensive examples. And even found a minor way to make css chunk extraction/compilation faster.

**Comment by lutzk** [comment]
just to add the info here:
i used the babel plugin but it did not worked
problem was my babel config:
the plugin was not applied when it was not the first in the plugins array:
dont worked:
```
'react-hot-loader/babel',
'dual-import',
```
worked: 
```
'dual-import',
'react-hot-loader/babel',
```

**Comment by psachs21** [comment]
I realize, digging through the various packages, that my issue is I'm trying to rework these plugins to work without SSR. I'm still learning all the ins and outs of webpack plugins, but I'm pretty sure these plugins won't support it without SSR (ie, on a static site)

**Comment by faceyspacey** [comment]
@lutzk good catch on the order thing. I don't suppose you can add a note to the readme about the order.

@psachs21 they'll work on a static site. Webpack bundles all your chunks in a way that even a static site can request additional chunks, so long as those additional chunk files also exist statically on the server. But if you just copy the bundle folder like you're supposed to do, they will all be there. So you don't need a real server setup to do dynamic imports and code splitting.

**Comment by psachs21** [comment]
@faceyspacey oh great! I'll update to the new version and give it a shot.

**Comment by faceyspacey** [comment]
@psachs21 check the components/Switcher.js file in the codesandbox to see `import()` in action in an SPA:

https://codesandbox.io/s/github/faceyspacey/redux-first-router-codesandbox/tree/master/?module=SksIQmo2S-

u need to have access to ur babelrc (to add babel-plugin-dual-import), so if ur using CRA, u'll have to eject.

**Comment by faceyspacey** [comment]
tho maybe CRA supports `import()` now. i dunno, i don't really use it.

**Comment by lutzk** [comment]
@faceyspacey 
i can add the info about the order to the readme - no problem

**Comment by lutzk** [comment]
@faceyspacey 
i was not able to reprodue the bug anymore
i tested it with various orderings of the plugins array but it just worked
when i dissable the plugin it shows numbered chunk names - as it should in the lates version
so i won't add a note about ordering to the readme :)

**Comment by psachs21** [comment]
@faceyspacey I think the babel-plugin-dual-import is where i get confused. It says it needs webpack-flush-chunks in order to serve the css and I can't figure out a way to integrate webpack-flush-chunks into my use of html-webpack-plugin. I think I need to include the window. __CSS_CHUNKS__ global to the page, but not sure how to do that with html-webpack-plugin.

The redux-first-router example doesn't show the webpack/babel setup to give me enough to work with.

**Comment by faceyspacey** [comment]
Are you doing an SPA or do you have SSR?

If you don't have SSR, you're gonna have to find another way to generate that cssChunks hash. 

Before going any farther, why don't you manually create it (i know chunk hashes will break it in the future), and just get it working. Once you get it manually working, and I understand your use-case a bit ore, we'll figure out an automated solution for you user case.

So manually embed this in the served HTML:

```js
<script>
  window.__CSS_CHUNKS__ = {
    Foo: '/static/Foo.css',
    'base/Page1': '/static/base/Page1.css',
    'base/Page2': '/static/base/Page2.css',
  }
</script>
```

then replace it with the appropiate keys and values until it works. Then we'll take it from there.

**Comment by psachs21** [comment]
It's an SPA. I believe if i manually insert the CSS_CHUNKS global, it'll work. So that becomes my challenge, having that work with the html-webpack-plugin. Figure out how i can wire webpack-flush-chunks into that. I'll spend some time looking into it and get back to you.

**Comment by psachs21** [comment]
I'll look into something similar to this: https://github.com/jouni-kantola/inline-chunk-manifest-html-webpack-plugin

If it's already grabbing the manifest, that may be enough for me to grab onto.

**Comment by faceyspacey** [comment]
Yea, you need to use a plugin that will get you the data you put in manually. But then you need a next step (a transformation of sorts) to be able to modify what is embedded.

I think this one will work:

https://github.com/FormidableLabs/webpack-stats-plugin

I'm not sure about with CRA--maybe it has to be ejected. Are you ejected?

I haven't used it, but that one has a `transform` option to take the stats and turn it into just the stats you want in the stats.json file. That way you don't have a huge stats file embedded in the page. 

Copy/paste this function https://github.com/faceyspacey/webpack-flush-chunks/blob/master/src/createApiWithCss.js#L166 within your transform so that `stats.assetsByChunkName` is transformed into what you want embedded on the page.

**Comment by psachs21** [comment]
No, this wasn't an ejected CRA app, it's pretty homegrown. In the process of modernizing it.

**Comment by psachs21** [comment]
Unfortunately, I'm having problems getting these plugins to plat nicely. If i provide inline-chunk-manifest-html-webpack-plugin with the webpack-stats-plugin, the assets are not exposed to the html-webpack-plugin. Will need to learn a fair bit more to figure out what I'm missing.

**Comment by psachs21** [comment]
Nevermind, figured it out. The default filenames between the packages are not the same so we need to pass in the appropriate filenames. Looks something like this:

```js
const createCssHash = function (assetsByChunkName, publicPath) {
	return Object.keys(assetsByChunkName).reduce(function b(hash, name) {
		if (!assetsByChunkName[name] || !assetsByChunkName[name].find) return hash;
		const file = assetsByChunkName[name].find(function a(f) { return f.endsWith('.css'); });
		if (file) hash[name] = publicPath + file;
		return hash;
	}, {});
};

new InlineChunkManifestHtmlWebpackPlugin({
	filename: 'manifest.json', // this MUST be the same filename provided to StatsWriterPlugin
	manifestPlugins: [
		new StatsWriterPlugin({
			transform: function a(data) {
				const publicPath = process.env.CDN_SERVER;
				return JSON.stringify(createCssHash(data.assetsByChunkName, publicPath));
			},
			filename: 'manifest.json'
		})
	],
	manifestVariable: '__CSS_CHUNKS__'
});
```

Note that I have a dynamic path (determined after build time) so I use a environment variable to set the publicPath (which I replace later to fit other environments)

**Comment by psachs21** [comment]
Also, that plugin HAS to go before the html plugin.

**Comment by psachs21** [comment]
Now my only problem is that images referenced in stylesheets (url(../images/login_banner.png)) are relative to their javascript import, instead of the directory of the actual file (in this case, src/styles/components.) Extract-css-chunks-webpack-plugin is trying to load the image from /containers/login_banner.png.

**Comment by faceyspacey** [comment]
use absolute paths instead.

...also, i forget, but you know you can just run the webpack compiler from javascript, and get the stats in the `run` callback like this:
![screen shot 2017-07-25 at 2 33 57 pm](https://user-images.githubusercontent.com/154732/28594860-52ff9f68-7146-11e7-8397-0370b111f961.png)

thats an example with a multi-compiler. a regular compiler doesnt use an array and u get the stats at `stats.toJson()`

i forget if it applies to your use case, but it's actually a lot nicer to do a lot of this stuff in js than from the command line.

**Comment by faceyspacey** [comment]
there's also some loader that will fix that for you too. and u pipe it to css loader, etc. i haven't needed it in a while, but it's probably a common combination of css-loader and file-loader.

**Comment by psachs21** [comment]
Hmm, fair point. I think I will change those paths to be absolute. Or at least to use my webpack configured moduleDirectories.

**Comment by yjzzcao** [comment]
Changing the code in getPath to this fixes during development when using [contenthash]:
```
function getPath(compilation, source, chunk) {
	return function(format) {
		return compilation.getPath(format, {
			chunk: chunk
		}).replace(/\[(?:(\w+):)?contenthash(?::([a-z]+\d*))?(?::(\d+))?\]/ig, function() {
			// var sourceValue = source && source._value || source; // catch a small bug during development when using [contenthash]
			var sourceValue = source && source._value !== undefined ? source._value : source;
			return loaderUtils.getHashDigest(sourceValue, arguments[1], arguments[2], parseInt(arguments[3], 10));
		});
	}
}
```
