### ISSUE TITLE
Preload css request instead of prefetch

### ISSUE THREAD

**Issue by ghisleouf** [faceyspacey/extract-css-chunks-webpack-plugin#260]
Hi there,

first of all, thanks for the plugin, it's great !

I've just integrated it to a VueJS ( and vuestorefront solution) and currently, I run a Lighthouse performance test ( like in this issue : https://github.com/faceyspacey/extract-css-chunks-webpack-plugin/issues/179).

Everything is extracted properly but, for one of the dynamically imported, it's called as prefetched :
`<link rel="prefetch" href="/dist/css/1.a8d3ad22.chunk.css">`

This is the first component of the page, a slider ... and Lighthouse asks me to preload it instead of prefetch it.

I have 2 questions : 

- how is the mitigation between prefetching and preloading done ?
- Is there a way to tweak it by component ? or a way to handle this issue ?

Thanks a lot for your help !

Best

**Comment by ScriptedAlchemy** [comment]
Open a pr and make the change. I’ll merge it. Preload is better to use.
