### ISSUE TITLE
Clarify package maintenance / add maintainers / mark as abandoned

### ISSUE THREAD

**Issue by willmorgan** [faceyspacey/extract-css-chunks-webpack-plugin#299]
Does this project require maintainers or external support in order to continue and merge PRs?

The formerly ubiquitous extract-text-webpack-plugin suggests using mini-css-extract-plugin, and this awesome package says (and mostly is) a new and improved version of that. However the fix to the broken insert function problem hasn't been released for a few weeks, and there are over a dozen open PRs at the time of writing - most of them simple patch updates (is Dependabot aiming for a Hacktoberfest tshirt? 🤷 )

I humbly suggest either requesting assistance by way of inviting new maintainers, or marking the project as deprecated/unsupported so it's correctly signposted.

**Comment by willmorgan** [comment]
Closing as I think this has already been conveyed enough elsewhere.

**Comment by ScriptedAlchemy** [comment]
I'll update the readme. This project merged with mini-css in 2018/2019. 

I maintain mini-css but use this project when I need to push specific updates ahead of mini css. 

It's less active, but I'll rebase off mini css to provide latest support for v5 and all other work I've put into mini css

**Comment by willmorgan** [comment]
@ScriptedAlchemy Much appreciated, thank you.
