### ISSUE TITLE
Hot reloading isn't working

### ISSUE THREAD

**Issue by eladchen** [faceyspacey/extract-css-chunks-webpack-plugin#30]
If I understand correctly, Using the examples outlined in the readme
When enabled this plugin will

- Support hot reload
- Add a css resource to the compilation assets
- Will allow to drop the style-loader for dev builds ( = Will update the link tags in the document ? ) 

If I'm correct, then none of the above works :(

+ It isn't very clear whether babel "dual-import" plugin is a peer dependency or not.

Is it ?

**Comment by faceyspacey** [comment]
exactly.

I'm in the middle of a transition to most users using [babel-plugin-universal-import], which has additional features for React Universal Component. 

For users that dont use RUC, dual-import will be what you still use.

What are you using for splitting? [React Universal Component](https://github.com/faceyspacey/react-universal-component)

...otherwise, I need a bit more info to figure out what's wrong for you. A repro would obviously make it very easy.

**Comment by eladchen** [comment]
I'll try and make one later this evening, you sound busy :)

**Comment by faceyspacey** [comment]
No, if you have the time, let's do it now. I just got to updating the docs for this. It's the final piece before launching React Universal Component 2.0. It's funny how the universe works.

I'll be updating the docs. If you don't have much time, maybe just paste me the relevant code. I'll help you get this working right now.

**Comment by faceyspacey** [comment]
ok, the first draft of the new docs is up:

https://github.com/faceyspacey/extract-css-chunks-webpack-plugin

That may clear some things up for you if you're new to the *Universal* family of packages. 

I realize putting all this stuff together is confusing--in about 2 weeks by the way all this stuff will consolidate under a new package `universal-render`.

**Comment by faceyspacey** [comment]
by the way what might have broke things for you is that `chunk` was called `cb` in webpack >= 3:

https://github.com/faceyspacey/extract-css-chunks-webpack-plugin/commit/56d2c92eaaad45fd69d19c399b02c60b92dbb138

it's working now.

**Comment by faceyspacey** [comment]
The demo is up with all the latest stuff:

https://github.com/faceyspacey/universal-demo

It relies on my PR to webpack which just got merged yesterday, so you have to checkout the PR to make it work. But it will likely be published within a week based on sokra's recent release rhythm.

The directions are in the demo readme.

**Comment by faceyspacey** [comment]
I'm gonna close this, as I'm very sure things are working.

**Comment by faceyspacey** [comment]
hit me on Reactlandia chat if there's anything else I can do:

https://gitter.im/Reactlandia/Lobby
