### ISSUE TITLE
webpack build error `Uncaught SyntaxError: Unexpected token /`

### ISSUE THREAD

**Issue by GuillaumeCisco** [faceyspacey/extract-css-chunks-webpack-plugin#33]
Hello, just tried to integrate `extract-css-chunks-webpack-plugin` to my project after successfully integrated react-universal-component and redux-first-router which are amazing :)

I encounter a problem by simply transforming my `ExtractTextPlugin` to `ExtractCssChunks`.
Here is my config:
```javascript
module: {
    rules: {
        test: /\.s?css$/,
        exclude: /node_modules\/^(?!prismjs)/,
        use: ExtractCssChunks.extract({
                fallback: 'style-loader',
                use: [
                    {
                        loader: 'css-loader',
                        options: {
                            sourceMap: true,
                            modules: true,
                            localIdentName: '[name]__[local]',
                        },
                    },
                    {
                        loader: 'postcss-loader',
                        options: {
                            sourceMap: true,
                        },
                    },
                    {
                        loader: 'sass-loader',
                        options: {
                            sourceMap: true,
                            sourceComments: true,
                        },
                    },
                ],
            }),
    }),
},
new ExtractCssChunks({
                filename: '[name].css',
                allChunks: false,
            },
        ),
```
The webpack compilation is OK and I have no warning, but when I try to load my website, I get an error:
`Uncaught SyntaxError: Unexpected token /`
which refer to this piece of built code:
```javascript
if (true) {
	module.hot.accept();
	if (module.hot.data) {
		var neverUsed = 1501864374091
		__webpack_require__("./node_modules/extract-css-chunks-webpack-plugin/hotModuleReplacement.js")("/", "index.css");
	}
}
require("__webpack_require__."./node_modules/extract-css-chunks-webpack-plugin/hotModuleReplacement.js"
```

Problem is at
```
//                             👇
require("__webpack_require__."./node_modules/extract-css-chunks-webpack-plugin/hotModuleReplacement.js"
```

I absolutely don't know why this problem occurs, and if I replace all my occurrences of `ExtractCssChunks` by `ExtractTextPlugin`, it works well, but I get the warning:

`[UNIVERSAL-IMPORT] no css chunks hash found at "window.__CSS_CHUNKS__". Make sure you are using: https://www.npmjs.com/package/extract-css-chunks-webpack-plugin . If you are not serving CSS, disregard this message.`

Sorry if this is not a bug, I'll put this question/issue on stackoverflow.

**Comment by faceyspacey** [comment]
I want to help you, but im in the middle of launching this:

https://medium.com/faceyspacey/announcing-react-universal-component-2-0-babel-plugin-universal-import-5702d59ec1f4

and then have to go to bed.

The warning means you need to use webpack-flush-chunks to serve the `cssHash`. 

As far as that error, that shouldn't be happening. My advice is to analyze all the docs in the webpack-flush-chunks repo as much as possible. There's also a docs folder with more. It's the downside of this "frameworkless" approach, but worth it for all the flexibility.

**Comment by GuillaumeCisco** [comment]
Hum ok, I though I did not need `webpack-flush-chunks` because I'm not using server side rendering yet.
I only use redux-first-router and react-universal-component, and wanted to get rid of the annoying warning: `[UNIVERSAL-IMPORT] no css chunks hash found at "window.__CSS_CHUNKS__". Make sure you are using: https://www.npmjs.com/package/extract-css-chunks-webpack-plugin . If you are not serving CSS, disregard this message.`

Should `extract-css-chunks-webpack-plugin` always work with `webpack-flush-chunks`  ?
Or `react-universal-component` should not display its warning message.

Thank you very much.
Good luck for releasing your new post.
And good night ;)

**Comment by faceyspacey** [comment]
You actually dont need it for SPAs. You're right. So disregard that warning--it's just a warning. In the future, i'll find a way to hide it for people with your use case.

Both packages dont need to be used together. You dont need webpack-flush-chunks. And definitely not in your case.

Here's what I would do: either make the demo look like the unique parts of your setup:

https://github.com/faceyspacey/universal-demo

or make your setup look like the demo.

Do as much as you can to combine the 2 in order to find what's causing the breakage, starting with the webpack config. Maybe try with less loaders. You know, just setup some simple files and try to find what could be breaking it. Plenty of people every day are getting it to work in Reactlandia chat. If you have any problems we can meet there this weekend :)

Dont forget to read today's article and spread the news!

**Comment by birdofpreyru** [comment]
Got the same problem. It would be great, if you provide an option to tell your plugin just to extract CSS into separate file per chunk, and do not mess with the loading mechanics and HMR.

**Comment by faceyspacey** [comment]
that's easy to add. u should just add it as a PR. look in the code for wherever those checks are made. it's in index.js and loader.js. it should be configurable by an option. 

...i think it's just the HMR that's relevant. the loading mechanics is handled by the babel plugin.

**Comment by birdofpreyru** [comment]
@faceyspacey I've never touched a code of Babel plugins before. Can you hint me, what is the meaning behind the default export and `pitch` function of `loader.js`, and how the Babel config options get in there?

Otherwise, the change I wanna make is indeed trivial.

**Comment by faceyspacey** [comment]
Pitch is basically just the actual code that is called at some point. Imagine its name was onReceiveFileToParse. The request arg it receives contains the info about the file to transform. Pitch and the default export are pretty much the same with pitch allowing for you to do more. 

In your case u just wanna find the it check and handle another test. Hope that helps.

**Comment by birdofpreyru** [comment]
Yeah, the question is, how do I get plugin's `options` object from within that default export and `pitch(..)`?
In `pitch(..)` I see the line `var query = loaderUtils.getOptions(this) || {};`, but I am not sure, are these the same options we set in `.babelrc` or not? In the default export function I see no options passed it at all.

**Comment by faceyspacey** [comment]
It's unrelated to babelrc. It's an options object u pass to the webpack plugin in your webpack config.

Yea it will take a bit more to pass em from index.js to the loader. Look near the top of index.js for where it deals with options.

We probably have to verify them too by adding them to the schema files.

**Comment by birdofpreyru** [comment]
My bad saying about babelrc. I am working on something else in parallel and two things got mixed in my head. What I wanted to say is that I want to introduce an additional option in plugin's config in Webpack like:
```
plugins: [
  new ExtractCssChunks({
    filename: '[name].css',
    justExtract: true,
  }),
]
```
I see how to update the options validation scheme, so that it is accepted. And it is trivial to update the code the way I want, I just see every `if` check like `NODE_ENV === 'development'` and add `!justExtract && NODE_ENV === 'development'`. What I really cannot see, is how to get the values of parameters passed to the plugin in Webpack's config at the point where these NODE_ENV checks are.

**Comment by faceyspacey** [comment]
Sorry i was on my phone before or I would have pasted the links.

This will pass it to the loader:

https://github.com/faceyspacey/extract-css-chunks-webpack-plugin/blob/master/index.js#L207

And then it should come in here:

https://github.com/faceyspacey/extract-css-chunks-webpack-plugin/blob/master/loader.js#L30

I could be wrong. What I would do next is open up the plugin in node_modules in an existing app and then log the result of `query`. Hopefully it has `justExtract` on it.

**Comment by birdofpreyru** [comment]
Well, if I use the plugin inside Wepack config rules like `ExtractCssChunks.extract(..)` the values of options, passed inside the plugin object constructor, do not arrive to the code point at your first link. Probably, I overlook something. Though, as far as my needs go, this patch makes the trick:

https://github.com/birdofpreyru/extract-css-chunks-webpack-plugin/commit/05740d4f477377fa0f56d6e8e3c89552bfeb44ba

What do you think? Should I create PR?

**Comment by faceyspacey** [comment]
left a comment over there. PR away once you figure that last thing out!

**Comment by GuillaumeCisco** [comment]
Just discovered that removing `fallback: 'style-loader',` make it works.
Maybe it will help.

**Comment by faceyspacey** [comment]
ok, then that's a solid solution. well done. I'm gonna close this.
