### ISSUE TITLE
Dashes in dynamic imports and css

### ISSUE THREAD

**Issue by mslf353** [faceyspacey/extract-css-chunks-webpack-plugin#37]
I recently switched to your Redux First Router and in that switch I started using dynamic imports using props with Universal Component.

After I did this, I've been getting dashes at the end of those imports and css files with extra css files hinting to less loader:

window.__CSS_CHUNKS__= {"pages/Account-":"/build-client/pages/Account-.css","pages/Register-":"/build-client/pages/Register-.css","pages/Home-":"/build-client/pages/Home-.css","pages/NotFound-":"/build-client/pages/NotFound-.css","pages/Register-styles-module-less":"/build-client/pages/Register-styles-module-less.css","pages/NotFound-styles-module-less":"/build-client/pages/NotFound-styles-module-less.css","pages/Account-account-module-less":"/build-client/pages/Account-account-module-less.css","app":"/build-client/app.css"}

I'm at a loss for what could cause this.

Another potentially related problem: The router seems to be ignoring my routesmap and everything goes to a /not-found. Although, if I go straight to a url that should work, ex. /register, then go anywhere else which results in a /not-found, then hit the back button it will actually load that page without styles and with a warning about missing styles from the window.__CSS_CHUNKS__ global var.

If I switch back to normal importing without using the props function for universal component, ex. const AboutRoute = universal(import('pages/About'), universalRouteOptions), it fixes css although routes still go to a /not-found.

Here is a repo that reproduces the problem: https://github.com/mslf353/Issue-Demo-For-Extract-CSS-Chunks-Webpack-Plugin

**Comment by faceyspacey** [comment]
One issue at a time:

make sure to upgrade webpack-flush-chunks and read this issue:

https://github.com/faceyspacey/react-universal-component/issues/28


then we'll deal with /not-found.

**Comment by mslf353** [comment]
Huh, I am on the latest webpack-flush-chunks.. and I do see the line:

var entryToFiles = function entryToFiles(entry) {
    return assets[entry] || assets[entry + '-'];
  };

In my flushChunks.js... weird

**Comment by faceyspacey** [comment]
it should work though. as long as your grouping your files like that there will be hyphens added though. that's a webpack issue. Keep in mind, chunks are being created for every file in those directories, which is why when using "dynamic expressions" it's best to have a clean directory with just the chunks/entry_points you want to create, and without an index.js file if you want to avoid hyphens. 

either way, i'd pick one of the 2 problems to solve first. solve the /not-found issue first. then move back to imports with dynamic expressions. possibly skip doing dynamic imports altogether until routing works. Right now trying to solve 2 problems at once is likely causing too many problems to properly sift through. 

I'll checkout your repro after you've tried a few of these things. I'll probably have time over the weekend. My guess is you can at least solve the routesMap issue. Remember, don't do the code splitting until the routesMap issue is solved. Then introduce the additional complexity.

**Comment by faceyspacey** [comment]
also good find, looking into the `entryToFiles` code.

**Comment by mslf353** [comment]
Thanks for your help so far, guessing I'm just missed something dumb. I do see the routes map loaded in the location reducer but all links end up producing a not found action even though they show the correct url before clicking. I am using redux-first-router-link fyi

I might have gotten closer, I just tried dispatching a custom action using redux dev tools and got an error from it saying: "Cannot read property 'location' of undefined"

Root reducer looks like this if it matters:

import { combineReducers } from 'redux';
import { reducer as form } from 'redux-form'

import page from 'pages/reducer';

export default location => combineReducers({
	location,
	form,
	page
});

**Comment by faceyspacey** [comment]
remove the routerOptions:

https://github.com/mslf353/Issue-Demo-For-Extract-CSS-Chunks-Webpack-Plugin/blob/master/src/routerOptions.js#L16

ur not using them

and ur routes are all string based. they would only work if ur routes were objects. see how it's trying to access the `role` key on the route. u can access properties on strings that don't exist, but still. ...try to remove all the stuff ur not using.

**Comment by faceyspacey** [comment]
createServerHistory isn't correct:

https://github.com/mslf353/Issue-Demo-For-Extract-CSS-Chunks-Webpack-Plugin/blob/master/src/app.jsx#L20

it accepts an options argument like this:

```js
createServerHistory({ initialEntries: [request.path] })
```

also ur shipping the memory history to the client, which u dont wanna do, since that adds to bundle size.

**Comment by mslf353** [comment]
@faceyspacey Ok, well... This is looking like the result of a long week rather than an issue with the repo. I'll go ahead and close this and sorry for bugging you. Thanks for pointing things out anyways. Have an amazing weekend!
