### ISSUE TITLE
Support chunkFilename options

### ISSUE THREAD

**Issue by alt-j** [faceyspacey/extract-css-chunks-webpack-plugin#39]
In the case where I want all my js chunks to be created in a separate directory I use `output.chunkFilename` webpack options.
For css I want the same (each css chunk be in the same folder with js chunk).

Example:
```js
module.exports = {
  entry: {index: 'src/index.js'},
  output: {
    filename: 'build/[name]/[name].js',
    chunkFilename: 'build/chunks/[name]/[name].js',
  },
  module: {
    rules: [
      {
        test: /\.css$/,
        use: ExtractCssChunks.extract({
          use: {loader: 'css-loader'}
          }
        })
      }
    ]
  },
  plugins: [
    new ExtractCssChunks({filename: 'build/[name]/[name].css'}),
  ]
}
```
Actual all css chunks to be created in `build/` folder instead of `build/chunks`.

**Comment by faceyspacey** [comment]
Did you ever figure this out?  It likely needs a PR. I'm going to close this, as I won't have time to address it.
