### ISSUE TITLE
Styles order for webpack v3

### ISSUE THREAD

**Issue by mike1808** [faceyspacey/extract-css-chunks-webpack-plugin#41]
Looks like there is the same issue for this plugin https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/548

I had that issue when I was using extract-text and it was fixed in the new release. However, when I switched to extract-css-chunks that issue appeared again.

**Comment by jdeal** [comment]
I think this PR fixes it: https://github.com/faceyspacey/extract-css-chunks-webpack-plugin/pull/42
