### ISSUE TITLE
Support for object loader notation?

### ISSUE THREAD

**Issue by mnpenner** [faceyspacey/extract-css-chunks-webpack-plugin#5]
node v7.9.0
ubuntu 16.04

I can't seem to get this to work with webpack 2's object notation for the loaders. e.g.

```js
{
    test: /\.css$/,
    use: ExtractCssChunks.extract({
        use: {
            loader: 'css-loader',
            options: {
                localIdentName: '[name]__[local]--[hash:base64:5]',
            }
        }
        ,
    }),
},
```

That should work, no?

**Comment by faceyspacey** [comment]
Then they likely is an issue with extract text webpack plugin as well. Check commits to their repo in the last month and make a pr with the same change they had.

It's working with the string right?

**Comment by mnpenner** [comment]
> Then they likely is an issue with extract text webpack plugin as well.

Works fine with `extract-text-webpack-plugin`.

> Check commits to their repo in the last month and make a pr with the same change they had.

Sorry, don't have time to do that right now.

> It's working with the string right?

Yes, it does work with strings.

**Comment by faceyspacey** [comment]
excellent, then likely a small change needs to be made

**Comment by faceyspacey** [comment]
it works now. If you can, upgrade and let me know if it works for you.
