### ISSUE TITLE
Latest patch breaks webpack 2 support

### ISSUE THREAD

**Issue by baldurh** [faceyspacey/extract-css-chunks-webpack-plugin#50]
The use of `chunk.sortModules();` breaks Webpack 2 support.
https://github.com/faceyspacey/extract-css-chunks-webpack-plugin/blob/master/index.js#L257

**Comment by faceyspacey** [comment]
We are only doing webpack 3 unfortunately. A PR may be accepted but I rather just not support 2 as 3 was a big change for webpack and a lot of refactoring were done there that make 2 and 3 very different.

**Comment by baldurh** [comment]
I see! When did that happen? Which release that is? This is not documented and certainly not reflected in `package.json`

**Comment by faceyspacey** [comment]
probably about 2 months ago.
