### ISSUE TITLE
chunk is not an instance of Chunk

### ISSUE THREAD

**Issue by adascal** [faceyspacey/extract-css-chunks-webpack-plugin#54]
I have a very tricky webpack config (extended version from `create-react-app`) and then I tried to replace `extract-text-webpack-plugin` with `extract-css-chunks-webpack-plugin` I got a nice error `chunk is not an instance of Chunk`

@faceyspacey can you give more information about `isChunk` function? I see it only in 2 places is used and not totally clear why.
https://github.com/faceyspacey/extract-css-chunks-webpack-plugin/blob/master/index.js#L357

And maybe it's possible to remove it? Cause even my "freaky" config working fine without it.

**Comment by faceyspacey** [comment]
probably can't remove it. Perhaps you're on an older version of webpack. This is meant for webpack 3+

**Comment by mike1808** [comment]
Got the same error on webpack v3.10.0

**Comment by gbakernet** [comment]
I had this issue on webpack 3.5.5 but not on webpack 3.10.0

**Comment by allocenx** [comment]
This must be wrong, i have latest versions of both webpack and this plugin and there is still this error? What am i doing wrong here? How so for others work and for some don't?

**Comment by mike1808** [comment]
I have the same error if I'm using globally installed webpack, if the webpack is locally installed and it's located in the project `node_modules` everything is OK

**Comment by allocenx** [comment]
@mike1808 actually my webpack is local installed, so thats why. Any other ideea why? I added babel universal plugin aswell to the .babelrc file...

**Comment by faceyspacey** [comment]
I opened up a discussion on the PR that introduced this code here:

https://github.com/faceyspacey/extract-css-chunks-webpack-plugin/pull/29

Please post any information there.

**Comment by manjula91** [comment]
I am also facing the same issue webpack version is 3.8.1

**Comment by faceyspacey** [comment]
This PR: https://github.com/faceyspacey/extract-css-chunks-webpack-plugin/pull/67 which was just merged fixes this. Please let me know if anyone is still having issues.
