### ISSUE TITLE
This does not seem to work with webpack-dev-server

### ISSUE THREAD

**Issue by allocenx** [faceyspacey/extract-css-chunks-webpack-plugin#56]
Basically, whenever i start to use webpack-dev-server along with this plugin i get this error `throw new Error(typeof error === 'string' ? error : 'chunk is not an instance of Chunk');`. Anyone knows a fix or something?

**Comment by faceyspacey** [comment]
check this issue which has now been re-opened:

https://github.com/faceyspacey/extract-css-chunks-webpack-plugin/issues/54
