### ISSUE TITLE
Usage with Next.js?

### ISSUE THREAD

**Issue by lucasconstantino** [faceyspacey/extract-css-chunks-webpack-plugin#59]
Any instructions on how to use this with [Next.js](https://github.com/zeit/next.js/)?

**Comment by faceyspacey** [comment]
Not from me, but if you're using Redux, I recommend using in combination with https://github.com/faceyspacey/redux-first-router and https://github.com/faceyspacey/react-universal-component . Far better than Next.js and without being locked into a framework.

**Comment by nisargrthakkar** [comment]
Any example for Next.JS ??

**Comment by sanishkr** [comment]
Can some please provide an example repo link to its usage with nextjs?
