### ISSUE TITLE
Strings need to be escaped in the loader

### ISSUE THREAD

**Issue by satazor** [faceyspacey/extract-css-chunks-webpack-plugin#6]
I'm trying this plugin but I'm having syntax errors on compilation because https://github.com/faceyspacey/extract-css-chunks-webpack-plugin/blob/master/loader.js#L136 and https://github.com/faceyspacey/extract-css-chunks-webpack-plugin/blob/master/loader.js#L137 needs to be escaped (quotes).

Here's some input for you to use in tests:
```
var moduleId = '/Users/andrecruz/Work/moxy/moxy/react-with-moxy-scripts/node_modules/css-loader/index.js?{"modules":true,"sourceMap":true,"importLoaders":1,"camelCase":"dashes","localIdentName":"[name]__[local]___[hash:base64:5]!"}!/Users/andrecruz/Work/moxy/moxy/react-with-moxy-scripts/node_modules/postcss-loader/index.js?{"plugins":[null,null,null,{"version":"5.2.17","plugins":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],"postcssPlugin":"postcss-cssnext","postcssVersion":"5.2.17"}]}!/Users/andrecruz/Work/moxy/moxy/react-with-moxy/src/pages/error/internal-error/InternalError.css'
```

**Comment by faceyspacey** [comment]
Thanks for the find. I won't have time for a bit. A PR would be welcome.

**Comment by satazor** [comment]
I'm currently evaluating this plugin and I will certainly make a PR if I find it valuable to use in https://github.com/moxystudio/react-with-moxy-scripts

**Comment by faceyspacey** [comment]
OK. fyi, I didn't update any of the tests from `extract-text-webpack-plugin`. It's still very much in a pre-release phase, as some things are going to change: *React Loadable* is going to get half the code from `webpack-flush-chunks` via a PR that will hopefully soon be accepted. `webpack-flush-chunks` will likely be renamed `react-loadable-flush-chunks`, even though it will still be useable if you aren't using *React Loadable*. 

Neither won't affect this, but there's things to be done to get this all ship shape. Any help is much appreciated.

**Comment by satazor** [comment]
@faceyspacey It seems everything is working as expected, congratulations! This is a huge improvement over extract test.

I will make a PR later today with the fixes. Dunno about the tests though, what do you suggestion?

Additionally, and this is minor, but I would like to be able to tweak the `no_css` to be `no-css` to follow our file naming convention. Perhaps we could add a an option for that?

**Comment by satazor** [comment]
Oops, btw PR done at #7

**Comment by faceyspacey** [comment]
I agree. let's change it to have hyphens by default, but also be configurable. 

...tests...this won't be the most fun package to write tests for unfortunately, but it needs to happen sooner than later. 

glad u got it working.
