### ISSUE TITLE
Typescript types?

### ISSUE THREAD

**Issue by leebenson** [faceyspacey/extract-css-chunks-webpack-plugin#64]
I'm using the @faceyspacey universe of components (awesome work!), and this one stood out as not having Typescript types.

Any plans to add?

**Comment by faceyspacey** [comment]
Glad u like it...None, but feel free to PR

**Comment by ScriptedAlchemy** [comment]
Pr would be much appreciated @leebenson

**Comment by leebenson** [comment]
would love to help, but I've moved on to styled components at present, so this is no longer part of my workflow. I'll go ahead and close.
