### ISSUE TITLE
chunk is not an instance of Chunk

### ISSUE THREAD

**Issue by oupirum** [faceyspacey/extract-css-chunks-webpack-plugin#66]
Hello
`extract-css-chunks-webpac-plugin@2.0.18`
`webpack@3.10.0`

I got an error `chunk is not an instance of Chunk` and explored it. This is because of second instance of webpack, I guess.
Imagine the following project structure:
```
package.json
...
node_modules/
    webpack@3.10.0
    extract-css-chunks-webpack-plugin@2.0.18
    ...
tests/
    package.json
    node_modules/
        webpack@3.10.0
        ...
    spec/
        ...
```
When I run unittests from `tests/` directory, I got `chunk is not an instance of Chunk` on `extract-css-chunks-webpack-plugin/index.js:359`
```
if (!(chunk instanceof Chunk)) {
    throw new Error(typeof error === 'string' ? error : 'chunk is not an instance of Chunk');
}
```
This is because of extract-css-chinks plugin uses webpack from root of project, but tests directory has second instance of webpack, so `instanceof` gives wrong result.
YES, I really need second webpack (same version) in tests directory.

Could you please fix this?

For example, using 
```
if (!(chunk.constructor.name === 'Chunk')) {
```
or
```
if (!chunk || (
    !chunk.modulesIterable &&
    !chunk.forEachModule &&
    !chunk.modules
)) {
```

**Comment by threehams** [comment]
So that's why this is happening. I'm not intentionally using multiple instances of Webpack, but the project I'm using this with is pretty complex, so it doesn't surprise me.

**Comment by faceyspacey** [comment]
Fixed by: https://github.com/faceyspacey/extract-css-chunks-webpack-plugin/pull/67
