### ISSUE TITLE
Time to move to Emotion?

### ISSUE THREAD

**Issue by dawidvdh** [faceyspacey/extract-css-chunks-webpack-plugin#68]
Hi, I just wanted to get an opinion here, since Emotion now supports IE11 do you think its time to move over?

If so would love to see documentation of how it all fits in the ecosystem, I am busy integrating it my side but I have a feeling that I am not fitting it in quite right, you can view it here https://github.com/madeagency/reactivity/tree/feature/transition-emotion (still very much experimenting)

**Comment by rherwig** [comment]
Having looked at the docs of emotion, I don't quite get the difference to styled-components. Care to help me out? :-)

**Comment by zackljackson** [comment]
I’ll need to look closer. But generally I am very against anything that isn’t a real css file. 

The performance implementations are pretty bad. With styled components, running my own benchmarks, I saw major performance decay on the client side. 

There’s many reasons, but I don’t wanna list it unless you want to hear. 

Pretty much I work with a guy who was behind some of googles web products (Frontend). His opinion on the matter along with my own tests, is why I’m against anything but real css files

**Comment by rherwig** [comment]
@zackljackson I would very much like you to elaborate further on that topic are provide some resources to read about it. I have always been biased towards css modules as well, but am currently looking into css-in-js and could use some resources especially on performance

**Comment by zackljackson** [comment]
Okay I’ll put something together. 
Pretty much, as fun as css in js looks and feels to us, it’s a bad practice. 

I say it with gritted teeth man - i loved css-in-js and even had ways to significantly compress the delivery bytessize. But it’s not good for browsers

**Comment by zackljackson** [comment]
Not forgotten about this. Just working on flush chunks and aggressive code splitting support. I’ve got a medium article that touches on some of this at a high level. Mostly around development use. 

I’ll formulate a good response soon guys

**Comment by ScriptedAlchemy** [comment]
Okay pretty much 

CSS-in-JS causes many performance issues. 
Remember, nothing is faster than the DOM / Native Browser Internals

**So what are we losing here**
* No ability to cache styles separate from JS
* * A small font size change means busting other files too
* * Imagine 400 deploys a day to a site getting 10 million hits a day... ouch
* Time to First Meaningful Paint is much longer. 
* * The page sits blank for a while as the browser cannot paint anything ahead of time
* You reduce the Compile, Execution, Render, Rasterization, and Pains all to one thread and all at the same time, usually the browser "warms up" using css to know what to expect before hand. 
* styled components must be bootstrapped before the react component, which delays the initialization of the react app. 
* You cannot optimize css at all, leading to more bloat. 
* In most cases you end up with FOUT - one way to get around it is inline styles for the initial render
* * Inline styles make the page larger and will ultimately render-block the site.
