### ISSUE TITLE
Error message with `entry` as function

### ISSUE THREAD

**Issue by sdvg** [faceyspacey/extract-css-chunks-webpack-plugin#76]
Version: 3.0.5

My Webpack config defines `entry` as a function instead of string or array.

Looks like this for me:

```
entry: () => {
  const main = path.resolve(sourceDirectory, `index.js`);

  return IS_PRODUCTION ? main : [main, `webpack-hot-middleware/client?reload=true`];
},
```

This causes your plugin to write "Something went wrong: contact the author" to the console.

I traced the bug to here: https://github.com/faceyspacey/extract-css-chunks-webpack-plugin/blob/master/src/index.js#L27

This works well with strings and arrays, but not with a function.

**Comment by ScriptedAlchemy** [comment]
@sdvg Thanks for reporting this. Ill push an update tomorrow

**Comment by zackkirsh** [comment]
@sdvg its on a next tag on npm

https://www.npmjs.com/package/extract-css-chunks-webpack-plugin

let me know if that works and ill do a release

**Comment by zackkirsh** [comment]
`npm i extract-css-chunks-webpack-plugin@next`

**Comment by sdvg** [comment]
@zackkirsh I tried it, looks good 👍 

Thanks a lot for the fast fix :)

**Comment by ScriptedAlchemy** [comment]
I’ll release it today! Much appreciate your time reporting this
