### ISSUE TITLE
How can I log what is happening

### ISSUE THREAD

**Issue by dagda1** [faceyspacey/extract-css-chunks-webpack-plugin#77]
Hi,

I have an issue with my setup:

```
        {
          test: /\.(css|scss|sass)$/,
          use:  [
                ExtractCssChunks.loader,
                {
                  loader: 'css-loader',
                  options: {
                    importLoaders: 2,
                    modules: true,
                    getLocalIdent: getLocalIdent,
                    minimize: isProduction
                  }
                },
                { loader: 'postcss-loader', options: postcssOptions },
                { loader: 'sass-loader', options: sassOptions }
              ]
        }
```
If I have a scss file in the same directory as a typescript tsx file then the the typescript file does not get transpiled.

If I remove the scss file then the typescript file gets rendered.

I have no idea how to log what is happening apart from console logging all over node_modules.

Surely there is a better way?

**Comment by ScriptedAlchemy** [comment]
I doll need to see the whole webpack config. Are you using the whole universal suit?

**Comment by ScriptedAlchemy** [comment]
This is related to css modules HMR

try `extract-css-chunks-webpack-plugin@next` and let me know if thats any better. Im working on a fix for this

**Comment by dagda1** [comment]
My webpack is split across a few files for server and client, [here](https://github.com/dagda1/cuttingedge/blob/master/packages/devtools/webpack/common.js) is the common one.

I have tried installing `@next` but get the same error.

> VM5167 main.29f4c1b6.js:72019 WebSocket connection to 'ws://localhost:3000/sockjs-node/863/431f04xa/websocket' failed: Connection closed before receiving a handshake response

YOu can see it in [this](https://github.com/dagda1/cuttingedge) repo if you 

```
yarn install
yarn start
```

In the root.

**Comment by ScriptedAlchemy** [comment]
What makes you think it’s related to css chunks plugin?
