### ISSUE TITLE
extract-css-chunks-webpack-plugin breaks in IE11

### ISSUE THREAD

**Issue by nirbhaymandelia** [faceyspacey/extract-css-chunks-webpack-plugin#83]
I have encounter an issue while using this plugin it breaks in Internet Explorer 11. further narrow down the problem the root cause is arrow function inside `hotModuleReplacement.js` right now hotModuleReplacement is not getting transpiled with babel causing this issue. could you please look into it.
I try out three versions 3.0.5, 3.0.6, 3.0.7 and issue exist in all the three version.

**Comment by ScriptedAlchemy** [comment]
Fixing now, thank you!

**Comment by ScriptedAlchemy** [comment]
https://github.com/faceyspacey/extract-css-chunks-webpack-plugin/pull/85

**Comment by ScriptedAlchemy** [comment]
Let me know if this solves it @nirbhaymandelia `npm i extract-css-chunks-webpack-plugin@next`

**Comment by nirbhaymandelia** [comment]
No, Now I see destructuring objects `const { forEach } = Array.prototype;` in line 7 causing problem.

**Comment by ScriptedAlchemy** [comment]
@nirbhaymandelia  3.0.8-beta.2 try that?

**Comment by kevinlaw91** [comment]
Hi, i tested beta.2 and template literals are still causing issue.

**Comment by nirbhaymandelia** [comment]
@ScriptedAlchemy try https://babeljs.io/repl/

**Comment by ScriptedAlchemy** [comment]
Released beta.3, sorry that part came from someone else so i didn't think to check it!!
`npm i extract-css-chunks-webpack-plugin@next`

**Comment by kevinlaw91** [comment]
Hi @ScriptedAlchemy I believe that you have fixed the wrong file. 😅
I have tested that the plugin will work after fixing template literals in L35, 37 and 68 of `hotModuleReplacement.js`. Btw, thanks for your great plugin.

**Comment by ScriptedAlchemy** [comment]
@kevinlaw91 Can you share your `hotModuleReplacement.js` file with me?

**Comment by ScriptedAlchemy** [comment]
Okay @kevinlaw91 @nirbhaymandelia  I updated the next tag

Please, once more:  `npm i extract-css-chunks-webpack-plugin@next`

Apologies for the back and fourth on this one

**Comment by kevinlaw91** [comment]
Error in `hotLoader.js` when running webpack build. You should revert the previous `hotLoader.js` fix

**Comment by ScriptedAlchemy** [comment]
Okay done and om NPM
