### ISSUE TITLE
Incorrect statement in the readme

### ISSUE THREAD

**Issue by timneutkens** [faceyspacey/extract-css-chunks-webpack-plugin#84]
> Next.js's styled-jsx, by the way, doesn't even work on the server--not so good when it comes to flash of unstyled content (FOUC).

https://github.com/zeit/styled-jsx#server-side-rendering

styled-jsx has supported server-side rendering ever since it was first released, so I'm not sure what lead to this claim 🤔 Otherwise we'd love an example so it can be fixed.

**Comment by ScriptedAlchemy** [comment]
@faceyspacey was this the case at the time of writing? or is there a still an issue. 

@timneutkens confirming with the author and will remove / update / give an example 😄

**Comment by lfades** [comment]
Hello, I also found it weird and ended up here, any updates ?

**Comment by ScriptedAlchemy** [comment]
Ill remove this, sorry fellas

**Comment by ScriptedAlchemy** [comment]
Review this PR and let me know if i missed anything, on my iPad and editing files sucks.

Again, sorry about the inaccuracy

https://github.com/faceyspacey/extract-css-chunks-webpack-plugin/pull/147
