### ISSUE TITLE
Async loading

### ISSUE THREAD

**Issue by zahorovskyi** [faceyspacey/extract-css-chunks-webpack-plugin#86]
Hi guys.
Your plugin is great and works fine, but I ran into a problem when I migrate from webpack 3 to webpack 4.

In previous version (for webpack 3) of extract-css-chunks-webpack-plugin you didn't manage style loading for async chunks, you created css chunks but didn't connected to the page. But in latest version you fix this problem and now plugin connect css to the page when related js async chunks loaded.

In my project I already have logic for connecting styles and I have complex cases when I need to remove or re-connect styles, and it's ok for me.
So, my question is next:
Do we have some way to disable async css chunks loading?
I create small fork just for check my theory:
https://github.com/zahorovskyi/extract-css-chunks-webpack-plugin/commit/d67a7dff4e7449c212fbb126dd379e9b38bb3dc0#diff-1fdf421c05c1140f6d71444ea2b27638R356
https://github.com/zahorovskyi/extract-css-chunks-webpack-plugin/commit/d67a7dff4e7449c212fbb126dd379e9b38bb3dc0#diff-4a921339b635f5dff3f097ef18fa9532R29
Do not pay attention to tests and dist changes, it's just for check.

**Comment by ScriptedAlchemy** [comment]
This seems outside the scope of my plugins intentions. 

If you want to load styles on demand, you can always just `import()` it as needed.
