### ISSUE TITLE
Ability to tweak no_css

### ISSUE THREAD

**Issue by satazor** [faceyspacey/extract-css-chunks-webpack-plugin#9]
This issue is to discuss the option to be able to specify how `no_css` is appended to the file.

I think the most flexible way is to specify an option that is a function. The default function should append `no-css`.

```js
new ExtractCssChunks({
   noCssFilename: (filename, asset) => filename.replace(/\.js$/, '.no-css.js'),
});
```
The function receives the filename along with the `asset` object from webpack so that we can do crazy stuff, like adding `no-css` after/before chunkhash etc.

Thoughts?

**Comment by satazor** [comment]
//cc @faceyspacey

**Comment by faceyspacey** [comment]
hey brother, we talked about this a while ago. It's a good idea. It's just low priority for me. I'm gonna close this but if you want to make a PR, i'll gladly merge it. 

here's where you implement it:

- assign the function (or default) to `this. noCssFilename` here:
https://github.com/faceyspacey/extract-css-chunks-webpack-plugin/blob/master/index.js#L137

- execute it here:
https://github.com/faceyspacey/extract-css-chunks-webpack-plugin/blob/master/index.js#L371

```js
var newName = this.noCssFilename(filename, asset);
```

...ps, later today I'm finally releasing all this stuff (i.e. more publicly). keep a look out, there may be some features useful to you.

**Comment by satazor** [comment]
👍
